// Generated by CoffeeScript 1.12.2
(function() {
  var Room;

  Room = (function() {
    module.exports = Room;

    Room.Data = require('data/Room.json');

    function Room() {}

    return Room;

  })();

}).call(this);
