// Generated by CoffeeScript 1.12.2
(function() {
  var Data;

  Data = (function() {
    module.exports = Data;

    function Data(stream, store, room, cust, book) {
      this.stream = stream;
      this.store = store;
      this.room = room;
      this.cust = cust;
      this.book = book;
    }

    Data.prototype.open = function() {};

    Data.prototype.insert = function() {};

    Data.prototype.select = function() {};

    return Data;

  })();

}).call(this);
