// Generated by CoffeeScript 1.12.2
(function() {
  var Firestore, Store,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Store = require('js/store/Store');

  Store.Firebase = require('firebase');

  Firestore = (function(superClass) {
    extend(Firestore, superClass);

    module.exports = Firestore;

    function Firestore(stream, uri, config1) {
      this.config = config1;
      Firestore.__super__.constructor.call(this, stream, uri, 'Firestore');
      this.fb = this.init(this.config);
      this.anon();
      this.fd = Store.Firebase.database();
    }

    Firestore.prototype.init = function(config) {
      Store.Firebase.initializeApp(config);
      Util.log('Firestore.init', config);
      return Store.Firebase;
    };

    Firestore.prototype.add = function(t, id, object) {
      var onComplete, tableName;
      tableName = this.tableName(t);
      onComplete = (function(_this) {
        return function(error) {
          if (error == null) {
            return _this.publish(tableName, id, 'add', object);
          } else {
            return _this.onerror(tableName, id, 'add', object, {
              error: error
            });
          }
        };
      })(this);
      return this.fd.ref(tableName + '/' + id).set(object, onComplete);
    };

    Firestore.prototype.get = function(t, id) {
      var tableName;
      tableName = this.tableName(t);
      return this.fd.ref(tableName + '/' + id).once('value', (function(_this) {
        return function(snapshot) {
          if (snapshot.val() != null) {
            return _this.publish(tableName, id, 'get', snapshot.val());
          } else {
            return _this.onerror(tableName, id, 'get', {}, {
              msg: 'Firestore get error'
            });
          }
        };
      })(this));
    };

    Firestore.prototype.put = function(t, id, object) {
      var onComplete, tableName;
      tableName = this.tableName(t);
      onComplete = (function(_this) {
        return function(error) {
          if (error == null) {
            return _this.publish(tableName, id, 'put', object);
          } else {
            return _this.onerror(tableName, id, 'put', object, {
              error: error
            });
          }
        };
      })(this);
      return this.fd.ref(tableName + '/' + id).set(object, onComplete);
    };

    Firestore.prototype.del = function(t, id) {
      var onComplete, tableName;
      tableName = this.tableName(t);
      onComplete = (function(_this) {
        return function(error) {
          if (error == null) {
            return _this.publish(tableName, id, 'del', {});
          } else {
            return _this.onerror(tableName, id, 'del', {}, {
              error: error
            });
          }
        };
      })(this);
      return this.fd.ref(tableName + '/' + id).remove(onComplete);
    };

    Firestore.prototype.insert = function(t, objects) {
      var onComplete, tableName;
      tableName = this.tableName(t);
      onComplete = (function(_this) {
        return function(error) {
          if (error == null) {
            return _this.publish(tableName, 'none', 'insert', objects);
          } else {
            return _this.onerror(tableName, 'none', 'insert', {
              error: error
            });
          }
        };
      })(this);
      return this.fd.ref(tableName).set(objects, onComplete);
    };

    Firestore.prototype.select = function(t, where) {
      var onComplete, tableName;
      if (where == null) {
        where = Store.where;
      }
      tableName = this.tableName(t);
      onComplete = (function(_this) {
        return function(snapshot) {
          var objects;
          if (snapshot.val() != null) {
            objects = Util.toObjects(snapshot.val(), where, _this.key);
            return _this.publish(tableName, 'none', 'select', objects, {
              where: where.toString()
            });
          } else {
            return _this.onerror(tableName, 'none', 'select', objects, {
              where: where.toString()
            });
          }
        };
      })(this);
      return this.fd.ref(tableName).once('value', onComplete);
    };

    Firestore.prototype.update = function(t, objects) {
      var onComplete, tableName;
      tableName = this.tableName(t);
      onComplete = (function(_this) {
        return function(error) {
          if (error == null) {
            return _this.publish(tableName, 'none', 'insert', objects);
          } else {
            return _this.onerror(tableName, 'none', 'insert', {
              error: error
            });
          }
        };
      })(this);
      return this.fd.ref(tableName).update(objects, onComplete);
    };

    Firestore.prototype.remove = function(t, where) {
      var onComplete, tableName;
      if (where == null) {
        where = Store.where;
      }
      tableName = this.tableName(t);
      onComplete = (function(_this) {
        return function(snapshot) {
          var key, object, objects;
          if (snapshot.val() != null) {
            objects = Util.toObjects(snapshot.val(), where, _this.key);
            for (key in objects) {
              object = objects[key];
              if (where(val)) {
                _this.fb.ref(t).remove(key);
              }
            }
            return _this.publish(tableName, 'none', 'remove', objects, {
              where: where.toString()
            });
          } else {
            return _this.onerror(tableName, 'none', 'remove', objects, {
              where: where.toString()
            });
          }
        };
      })(this);
      return this.fd.ref(t).once('value', onComplete);
    };

    Firestore.prototype.open = function(t, schema) {
      var onComplete, tableName;
      if (schema == null) {
        schema = {};
      }
      tableName = this.tableName(t);
      onComplete = (function(_this) {
        return function(error) {
          if (error == null) {
            return _this.publish(tableName, 'none', 'open', {}, {
              schema: schema
            });
          } else {
            return _this.onerror(tableName, 'none', 'open', {}, {
              schema: schema,
              error: error
            });
          }
        };
      })(this);
      return this.fd.ref().push(tableName, onComplete);
    };

    Firestore.prototype.show = function(t) {
      var keys, onComplete, tableName;
      if (t == null) {
        t = void 0;
      }
      tableName = t != null ? this.tableName(t) : this.dbName;
      keys = [];
      onComplete = (function(_this) {
        return function(snapshot) {
          return snapshot.forEach(function(key) {
            keys.push(key.key());
            return _this.publish(tableName, 'none', 'show', keys);
          });
        };
      })(this);
      if (t != null) {
        return this.fd.ref(tableName).once('value', onComplete);
      } else {
        return this.fd.ref().once('value', onComplete);
      }
    };

    Firestore.prototype.make = function(t, alters) {
      if (alters == null) {
        alters = {};
      }
      this.onerror(t, 'none', 'make', {}, {
        error: 'Store.make() not supported',
        alters: alters
      });
    };

    Firestore.prototype.drop = function(t) {
      var onComplete, tableName;
      tableName = this.tableName(t);
      onComplete = (function(_this) {
        return function(error) {
          if (error == null) {
            return _this.publish(tableName, 'none', 'drop', "OK");
          } else {
            return _this.onerror(tableName, 'none', 'drop', {}, {
              error: error
            });
          }
        };
      })(this);
      return this.fd.ref(tableName).remove(onComplete);
    };

    Firestore.prototype.on = function(t, id) {
      var onEvt, path, tableName;
      tableName = this.tableName(t);
      path = id(eq('')) ? tableName : tableName + '/' + id;
      onEvt = 'value';
      this.fd.ref(path).on(onEvt, (function(_this) {
        return function(snapshot) {
          var key, val;
          key = snapshot.name();
          val = snapshot.val();
          if ((key != null) && (val != null)) {
            return _this.publish(tableName, id, 'onChange', val, {
              key: key
            });
          } else if (val == null) {
            return _this.publish(tableName, id, 'onChange', {}, {
              key: key,
              msg: 'No Value'
            });
          } else {
            return _this.onerror(tableName, id, 'onChange', {}, {
              error: 'error'
            });
          }
        };
      })(this));
    };

    Firestore.prototype.isNotEvt = function(evt) {
      switch (evt) {
        case 'value':
        case 'child_added':
        case 'child_changed':
        case 'child_removed':
        case 'child_moved':
          return false;
        default:
          return true;
      }
    };

    Firestore.prototype.anon = function() {
      this.fb.auth().signInAnonymously()["catch"]((function(_this) {
        return function(error) {
          if (error == null) {
            return _this.publish('none', 'none', 'anon', 'OK');
          } else {
            return _this.onerror('none', 'none', 'anon', {}, {
              error: error
            });
          }
        };
      })(this));
    };

    Firestore.prototype.auth = function(tok) {
      this.fb.auth(tok, (function(_this) {
        return function(error, result) {
          if (error == null) {
            return _this.publish('', tok, 'auth', result.auth, {
              expires: new Date(result.expires * 1000)
            });
          } else {
            return _this.onerror('', tok, 'auth', {}, {
              error: error
            });
          }
        };
      })(this));
    };

    return Firestore;

  })(Store);

}).call(this);
