// Generated by CoffeeScript 1.12.2
(function() {
  var Firestore, Store,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Store = require('js/store/Store');

  Store.Firebase = require('firebase');

  Firestore = (function(superClass) {
    extend(Firestore, superClass);

    module.exports = Firestore;

    Firestore.EventOn = {
      value: "onVal",
      child_added: "onAdd",
      child_changed: "onPut",
      child_removed: "onDel",
      child_moved: "onMov"
    };

    Firestore.OnEvent = {
      onVal: "value",
      onAdd: "child_added",
      onPut: "child_changed",
      onDel: "child_removed",
      onMov: "child_moved"
    };

    function Firestore(stream, uri, config1) {
      this.config = config1;
      Firestore.__super__.constructor.call(this, stream, uri, 'Firestore');
      this.fb = this.init(this.config);
      this.auth();
      this.fd = Store.Firebase.database();
    }

    Firestore.prototype.init = function(config) {
      Store.Firebase.initializeApp(config);
      Util.log('Firestore.init', config);
      return Store.Firebase;
    };

    Firestore.prototype.add = function(t, id, object) {
      var onComplete, tableName;
      tableName = this.tableName(t);
      onComplete = (function(_this) {
        return function(error) {
          if (error == null) {
            return _this.publish(tableName, id, 'add', object);
          } else {
            return _this.onerror(tableName, id, 'add', object, {
              error: error
            });
          }
        };
      })(this);
      return this.fd.ref(tableName + '/' + id).set(object, onComplete);
    };

    Firestore.prototype.get = function(t, id) {
      var onComplete, tableName;
      tableName = this.tableName(t);
      onComplete = (function(_this) {
        return function(snapshot) {
          if ((snapshot != null) && (snapshot.val() != null)) {
            return _this.publish(tableName, id, 'get', snapshot.val());
          } else {
            return _this.onerror(tableName, id, 'get', {}, {
              msg: 'Firestore get error'
            });
          }
        };
      })(this);
      return this.fd.ref(tableName + '/' + id).once('value', onComplete);
    };

    Firestore.prototype.put = function(t, id, object) {
      var onComplete, tableName;
      tableName = this.tableName(t);
      onComplete = (function(_this) {
        return function(error) {
          if (error == null) {
            return _this.publish(tableName, id, 'put', object);
          } else {
            return _this.onerror(tableName, id, 'put', object, {
              error: error
            });
          }
        };
      })(this);
      return this.fd.ref(tableName + '/' + id).set(object, onComplete);
    };

    Firestore.prototype.del = function(t, id) {
      var onComplete, tableName;
      tableName = this.tableName(t);
      onComplete = (function(_this) {
        return function(error) {
          if (error == null) {
            return _this.publish(tableName, id, 'del', {});
          } else {
            return _this.onerror(tableName, id, 'del', {}, {
              error: error
            });
          }
        };
      })(this);
      return this.fd.ref(tableName + '/' + id).remove(onComplete);
    };

    Firestore.prototype.insert = function(t, objects) {
      var onComplete, tableName;
      tableName = this.tableName(t);
      onComplete = (function(_this) {
        return function(error) {
          if (error == null) {
            return _this.publish(tableName, 'none', 'insert', objects);
          } else {
            return _this.onerror(tableName, 'none', 'insert', {
              error: error
            });
          }
        };
      })(this);
      return this.fd.ref(tableName).set(objects, onComplete);
    };

    Firestore.prototype.select = function(t, where) {
      var onComplete, tableName;
      if (where == null) {
        where = Store.where;
      }
      tableName = this.tableName(t);
      onComplete = (function(_this) {
        return function(snapshot) {
          var objects;
          if ((snapshot != null) && (snapshot.val() != null)) {
            objects = Util.toObjects(snapshot.val(), where, _this.key);
            return _this.publish(tableName, 'none', 'select', objects, {
              where: where.toString()
            });
          } else {
            return _this.onerror(tableName, 'none', 'select', objects, {
              where: where.toString()
            });
          }
        };
      })(this);
      return this.fd.ref(tableName).once('value', onComplete);
    };

    Firestore.prototype.update = function(t, objects) {
      var onComplete, tableName;
      tableName = this.tableName(t);
      onComplete = (function(_this) {
        return function(error) {
          if (error == null) {
            return _this.publish(tableName, 'none', 'insert', objects);
          } else {
            return _this.onerror(tableName, 'none', 'insert', {
              error: error
            });
          }
        };
      })(this);
      return this.fd.ref(tableName).update(objects, onComplete);
    };

    Firestore.prototype.remove = function(t, where) {
      var onComplete, tableName;
      if (where == null) {
        where = Store.where;
      }
      tableName = this.tableName(t);
      onComplete = (function(_this) {
        return function(snapshot) {
          var key, object, objects;
          if ((snapshot != null) && (snapshot.val() != null)) {
            objects = Util.toObjects(snapshot.val(), where, _this.key);
            for (key in objects) {
              object = objects[key];
              if (where(val)) {
                _this.fb.ref(t).remove(key);
              }
            }
            return _this.publish(tableName, 'none', 'remove', objects, {
              where: where.toString()
            });
          } else {
            return _this.onerror(tableName, 'none', 'remove', objects, {
              where: where.toString()
            });
          }
        };
      })(this);
      return this.fd.ref(t).once('value', onComplete);
    };

    Firestore.prototype.make = function(t) {
      var onComplete, tableName;
      tableName = this.tableName(t);
      onComplete = (function(_this) {
        return function(error) {
          if (error == null) {
            return _this.publish(tableName, 'none', 'make', {}, {});
          } else {
            return _this.onerror(tableName, 'none', 'make', {}, {
              error: error
            });
          }
        };
      })(this);
      return this.fd.ref().set(tableName, onComplete);
    };

    Firestore.prototype.show = function(t) {
      var keys, onComplete, tableName;
      if (t == null) {
        t = void 0;
      }
      tableName = t != null ? this.tableName(t) : this.dbName;
      keys = [];
      onComplete = (function(_this) {
        return function(snapshot) {
          if (snapshot != null) {
            snapshot.forEach(function(child) {
              return keys.push(child.key);
            });
            return _this.publish(tableName, 'none', 'show', keys);
          } else {
            return _this.onerror(tableName, 'none', 'show', {}, {
              error: 'error'
            });
          }
        };
      })(this);
      if (t != null) {
        return this.fd.ref(tableName).once('value', onComplete);
      } else {
        return this.fd.ref().once('value', onComplete);
      }
    };

    Firestore.prototype.drop = function(t) {
      var onComplete, tableName;
      tableName = this.tableName(t);
      onComplete = (function(_this) {
        return function(error) {
          if (error == null) {
            return _this.publish(tableName, 'none', 'drop', "OK");
          } else {
            return _this.onerror(tableName, 'none', 'drop', {}, {
              error: error
            });
          }
        };
      })(this);
      return this.fd.ref(tableName).remove(onComplete);
    };

    Firestore.prototype.on = function(onEvt, t, id) {
      var onComplete, path, table;
      if (id == null) {
        id = 'none';
      }
      table = this.tableName(t);
      onComplete = (function(_this) {
        return function(snapshot) {
          var key, val;
          if (snapshot != null) {
            key = snapshot.key;
            val = snapshot.val();
            return _this.publish(table, id, onEvt, {
              onEvt: onEvt,
              table: table,
              key: key,
              val: val
            });
          } else {
            return _this.onerror(table, id, onEvt, {}, {
              error: 'error'
            });
          }
        };
      })(this);
      path = id === 'none' ? table : table + '/' + id;
      return this.fd.ref(path).on(Firestore.OnEvent[onEvt], onComplete);
    };

    Firestore.prototype.auth = function() {
      var onError;
      onError = (function(_this) {
        return function(error) {
          return _this.onerror('none', 'none', 'anon', {}, {
            error: error
          });
        };
      })(this);
      return this.fb.auth().signInAnonymously()["catch"](onError);
    };

    return Firestore;

  })(Store);

}).call(this);
