// Generated by CoffeeScript 1.12.2
(function() {
  var Menus;

  Menus = (function() {
    module.exports = Menus;

    function Menus(app, process, action) {
      this.app = app;
      this.process = process;
      this.action = action;
      this.name = 'Muse';
    }

    Menus.prototype.menus = function() {
      var all;
      all = [];
      if (this.process.platform === 'darwin') {
        all.push(this.macs());
      }
      all.push(this.file());
      all.push(this.edit());
      all.push(this.view());
      return all;
    };

    Menus.prototype.macs = function() {
      return {
        label: this.name,
        submenu: [
          {
            label: 'About ' + this.name,
            role: 'about'
          }, {
            type: 'separator'
          }, {
            label: 'Services',
            role: 'services',
            submenu: []
          }, {
            type: 'separator'
          }, {
            label: 'Hide ' + this.name,
            role: 'hide',
            accelerator: 'Command+H'
          }, {
            label: 'Hide Others',
            role: 'hideothers',
            accelerator: 'Command+Shift+H'
          }, {
            label: 'Show All',
            role: 'unhide'
          }, {
            label: 'Quit',
            accelerator: 'Command+Q',
            click: (function(_this) {
              return function() {
                return _this.app.quit();
              };
            })(this)
          }
        ]
      };
    };

    Menus.prototype.file = function() {
      return {
        label: 'File',
        submenu: [
          {
            label: 'New',
            accelerator: 'Command+N',
            click: (function(_this) {
              return function() {
                return _this.action.newf();
              };
            })(this)
          }, {
            label: 'Open',
            accelerator: 'Command+O',
            click: (function(_this) {
              return function() {
                return _this.action.open();
              };
            })(this)
          }, {
            label: 'Save',
            accelerator: 'Command+S',
            click: (function(_this) {
              return function() {
                return _this.action.save();
              };
            })(this)
          }, {
            type: 'separator'
          }, {
            label: 'Preferences',
            accelerator: 'Command+P',
            click: (function(_this) {
              return function() {
                return _this.action.pref();
              };
            })(this)
          }
        ]
      };
    };

    Menus.prototype.edit = function() {
      return {
        label: 'Edit',
        submenu: [
          {
            label: 'Undo',
            accelerator: 'Command+Z',
            click: (function(_this) {
              return function() {
                return _this.action.undo();
              };
            })(this)
          }, {
            label: 'Redo',
            accelerator: 'Command+U',
            click: (function(_this) {
              return function() {
                return _this.action.redo();
              };
            })(this)
          }, {
            type: 'separator'
          }, {
            label: 'Cut',
            accelerator: 'Command+X',
            click: (function(_this) {
              return function() {
                return _this.action.cut();
              };
            })(this)
          }, {
            label: 'Copy',
            accelerator: 'Command+C',
            click: (function(_this) {
              return function() {
                return _this.action.copy();
              };
            })(this)
          }, {
            label: 'Paste',
            accelerator: 'Command+V',
            click: (function(_this) {
              return function() {
                return _this.action.paste();
              };
            })(this)
          }, {
            label: 'Select All',
            accelerator: 'Command+A',
            click: (function(_this) {
              return function() {
                return _this.action.selectAll();
              };
            })(this)
          }, {
            type: 'separator'
          }, {
            label: 'Find',
            accelerator: 'Command+F',
            click: (function(_this) {
              return function() {
                return _this.action.find();
              };
            })(this)
          }, {
            label: 'Replace',
            accelerator: 'Command+R',
            click: (function(_this) {
              return function() {
                return _this.action.replace();
              };
            })(this)
          }
        ]
      };
    };

    Menus.prototype.view = function() {
      return {
        label: 'View',
        submenu: [
          {
            label: 'Close',
            accelerator: 'Command+W',
            click: (function(_this) {
              return function() {
                return _this.action.close();
              };
            })(this)
          }, {
            label: 'Skyline',
            click: (function(_this) {
              return function() {
                return _this.action.view('Skyline', '/public/index.html');
              };
            })(this)
          }, {
            label: 'Toggle Dev Tools',
            accelerator: 'Command+T',
            click: (function(_this) {
              return function() {
                return _this.action.toggleDevTools();
              };
            })(this)
          }
        ]
      };
    };

    return Menus;

  })();

}).call(this);
