
Good value, but completely unreliable hotel staff.
Posted Oct 5, 2016
Pros: Semi-cozy room that is very close to the entrance of RMNP.
Cons: The didn't have my reservation (reserved 3 months in advance) and also tried to claim that I hadn't paid (even though I had during check in).
Location: EXTREMELY close to the east entrance of Rocky Mountain National Park. Great location for quick access to many trailheads in the park.
Was this review helpful to you?
Poor service
2 out of 5

    by Carol from Kearney, NE

Poor service
Posted Sep 20, 2016
Pros: Convenient location to RMNP.
Cons: Most everything but mostly staff need to be present at desk and provide maid service!
Location: Just a couple miles away from RMNP and from down town Eastes Park.
Check in consisted of being handed a key and told where we could get extra towels, etc by helping ourselves in the office. There was no maid service for the four nights we stayed and we took out our own trash. The hide-a-bed in room was shot and had to move furniture to use it. Glad we brought an air mattress to use on the hide-a-bed. On evening had a question and owner was gone all evening. Another evening a new guest wanted to check in and told us they had been waiting over an hour for someone to show up to check them in.
Was this review helpful to you?
An aged and rubdown property should be closed
1 out of 5

    by Jay from Reston, VA

An aged and rubdown property should be closed
Posted Aug 23, 2016
I made a mistake to book the reservation before I read the website review. When I try to cancel my reservation and find out it would cost my half hotel fees. So I took a chance and I feel regret. The place is old, dirty, smell bad. The bathroom and shower are really bad. My wife and my daughter can't spend whole night because bad smell. Don't stay this place if you want to have good experience with Great Rocky Mountain.
Was this review helpful to you?
BettyMielke
1 out of 5

    by Betty from Cheyenne WY

BettyMielke
Posted Aug 17, 2016
Our cabin was very very dirty. It smelled like pets had urinated on the carpet
and it had not been clean. We did not stay. I would not recommend this cabin at all.
Was this review helpful to you?
Nice view but.....
2 out of 5

    by Mark from Albia IA

Nice view but.....
Posted Aug 8, 2016
We arrived and were informed we had to drive a mile to the cabin,
it's a good thing we had four wheel drive because the road was terrible.
We were told they had installed a new television system, it never worked in all the time we were there. The website states that we can walk straight out our backyard into Rocky Mountain National Park for a hike. I even asked the staff member who showed us the cabin when we checked in to make sure it was ok. When we started our hike we were immediately approached by a gentleman who told us we were trespassing on his land and had no right to be there. He was very surprised that the hotel was telling people they could walk right out their back door, he was friendly but definitely did not appreciate our presence. It was an embarrassing interaction.
Was this review helpful to you?
Awful beds
2 out of 5

    by A verified traveler

Awful beds
Posted Aug 4, 2016
Beds were terrible and it was supposed to accomdate 3 adults one child.
it was a trundle bed that wouldn't stay up or down .
Was this review helpful to you?
Quiet. Just what I needed
5 out of 5

    Review recommended
    for Everyone
    by A verified traveler

Quiet. Just what I needed
Posted Aug 3, 2016
Diana was awesome. She held a room for us when there were none in town.
The mix up was never a factor. She is first rate people. Skyline Cottages is great!!
Was this review helpful to you?
July 2016 RMNP
3 out of 5

    by A verified traveler

July 2016 RMNP
Posted Jul 28, 2016
This was the only place j could find that would let me book a single night in July. We had 2 days of hiking planned and need a 1 night stay. I had hoped to enjoy the location by the river but our unit was across the road and up the hill. It was adequate for our needs but it is old and tired.
Was this review helpful to you?
Flag this review as inappropriate
In disrepair and not too clean
2 out of 5

    by A verified traveler

In disrepair and not too clean
Posted Jul 17, 2016
Pros: Location
Cons: Add AC, paint and repair walls, furniture, television, carpet. Add AC.
Throw away or professionally repair broken and ripped furniture.
Location: Close to Estes Park, Rocky Mountain National Park, and YMCA.
All furniture except two tables in the living room need junked.
Holes and broken furniture. When sitting cushions sunk into the frame.
Given Wifi code but never able to connect.
Peeling paint and wallpaper, duck taped baseboard heaters.
Showers and vinyl floors and bathroom fixtures were clean.
Location is good along river with pleasant back porch.
Even the back porch had ripped and stained cushion.
 Management rigged up an extension cord from underneath the porch to power some equipment
 as the walk to the river was closed for repairs and use of extension cords to bedside lamps..
 Again question fire safety. Mattress fair. Dusty and dirty top of curtains, dirty old carpet,
 and wall hangings. No AC. Windows had to be propped open, broken and would not stay open.
 Pull string old light fixtures, question fire hazard in one bedroom.
 TV reception iffy with one television buzzing. Rooms were large but uncomfortably hot
 without AC two nights as the days were hot. Management not available at times.
 Wandered into the office to help ourselves to some well worn towels and fishing poles
 that were not in good repair. Could be nice with some upgrades and better management.
 Had to repeat requests to management who never seemed to remember what was previously requested.
 Unpleasant interaction.
Was this review helpful to you?
Disappointing accommodations
2 out of 5

    by Margie from Tucson, AZ

Disappointing accommodations
Posted Jul 15, 2016
Very outdated. Very uncomfortable bed. Tiny shower. Small bathroom. No A/C and only one working window. No room service. Good location, refrigerator, great parking.

Adorable cabins near creek and National Park
Posted May 23, 2016
Pros: The location was great and the cabin was very clean.
Cons: I really can't think of anything the property met my expectations.
Location: Roosevelt National Park located about 2 miles away. There is a bar/restaurant across the street. Estes Park is a short drive from the property.
I stayed in the cabins a little before the mountain season began. My cabin was perfect. Came with everything I needed. The porch for adorable and they had grills available for all of the cabins. The creek behind the cabins was beautiful and so relaxing to sit by. The property was about 2-3 miles from the National Park. Lots of restaurants nearby and bar walking distance from the property. The staff was very nice! I had a great time and will be back!

---------------------

“Terrible ”
Reviewed October 28, 2016 via mobile

This was the worst lodging experience of my life and completely ruined my vacation. Booked the upper north cottage for 3 people and 3 dogs for 2 nights with Diana. She said that she would only charge for 2 people and 1 dog when I made the reservation which was awesome. I called back requesting a 3rd night and left...
More
 Report
Helpful?
Thank Steveo834
Bill R
Level Contributor
14 reviews
8 hotel reviews
8 helpful votes
“Sleep in your car before u stay here”
Reviewed September 15, 2016 via mobile

If u like "authentic Estes" you mite enjoy this. 1940s built and not improved on. Hardly any river frontage, and that is the good part. This place is bad, and the manager well..........sleep in your car, it smells better, and you won't be insulted like we were. DONT STAY HERE.
 Report
Helpful?
Thank Bill R
judith l
Westminster, Colorado
Level Contributor
279 reviews
34 hotel reviews
69 helpful votes
“'Rustic' being a synonym for badly kept and maintained ( cabin #6)”
Reviewed August 2, 2016

On the plus side- great location streamside. Lovely porch. Furniture seems to have been found roadside, blinds, broken duct taped heaters, dirty everything, musty smells. Sleeps a dubious 12, if you are all in each others arm pits. One bathroom shared by all, by entering through someone's bedroom. I just think that the accommodations are minimal, and no expense was...
More
 Report
Helpful?
Thank judith l
Hoppia
Denver, Colorado
Level Contributor
63 reviews
8 hotel reviews
12 helpful votes
“Little cottages as expected, dated but clean”
Reviewed July 27, 2016

Our little cottage had what we needed, but was very dated, down to the threadbare sheets for the pullout couch bed for my daughter. I think that cottage should just be sold for two people, in order to fit the pullout, we had to move the table and chairs, and there was barely enough room to get around them. The...
More
 Report
Helpful?
Thank Hoppia
margie442015
Tucson, Arizona
Level Contributor
9 reviews
1 helpful vote
“Disappointing accommodations”
Reviewed July 15, 2016 via mobile

Cottage was very outdated and small. No room service. No A/C and only one working window. Uncomfortable bed. Tiniest shower ever. Small bathroom. Difficult to check in and out as staff was not in office and hard to find. Felt like we were a bother to them. Room was in a great location and had good parking. Also had a...
More
 Report
Helpful?
Thank margie442015
Terry N
Denver, Colorado
Level Contributor
57 reviews
18 hotel reviews
16 helpful votes
“I've stayed here twice and have been treated great!”
Reviewed October 5, 2015

The first time I stayed here the room I was in was great but they had a complaint about mice! I never saw one but it is common for people to do this to lower the bill! This is a resort town right outside Rocky Mountain National Park! Having a full kitchen with fridge, oven, stove and all the utensils...
More
 Report
Helpful?
Thank Terry N
eileen2951
Slinger, Wisconsin
Level Contributor
29 reviews
5 hotel reviews
7 helpful votes
“Comfortable but old”
Reviewed October 5, 2015

We stayed in the upper Skyline Cottage South. It was old, but comfortable. The people were nice enough. We arrived late at night and they stayed up to take us to the cottage. The majority of the place was clean (except for the plate of old cooked bacon in the microwave; the gross bottom of the garbage can in the...
More
 Report
Helpful?
1Thank eileen2951
Tridun
Golden, Colorado
Level Contributor
3 reviews
5 helpful votes
“Terrible Experience- Overpriced for a rundown cabin”
Reviewed September 28, 2015

We booked the Upper Skyline cabin online for 3 nights. Whilst driving to the place we got a call from the owner to say could we get there before 3pm as they had to leave for a family event even though check-in time was after 3pm. On arriving the owner was surprised that there were 4 of us and 3...
More
 Report
Helpful?
2Thank Tridun
Rand1995
Cheyenne, Wyoming
Level Contributor
3 reviews
1 helpful vote
“Don't believe the pictures”
Reviewed September 27, 2015

We stayed the weekend only because we couldn't get a refund. The pictures showed a very nice cabin, but what we had was a run down room. The bed didn't fit the area, the spa tub did not work, the bathroom was gross. The pillow stunk and had to be 10 years old. Paid way too much for the stay!...
More
 Report
Helpful?
1Thank Rand1995
Dana P
Denver, Colorado
1 review
“Beautiful, quiet and cozy with gorgeous river view”
Reviewed September 9, 2015

My Mom and I have an annual tradition to take a weekend away in Estes toward the end of the summer. We've stayed at a number of other places over the years, but our recent location - Skyline Cottages - was our favorite so far, because the river view is unbeatable, and the owner is sweet, friendly and accomodating to...
More
 Report
Helpful?
Thank Dana

“Lovely Place!”
Reviewed August 6, 2015

The Skyline Cottages are conveniently located just outside the entrance to Rocky Mountain National Park. They are very reasonably priced compared to other properties in the area for their location and access to the park is excellent. We had a great time and the owners are some of the nicest and most accommodating hosts we have dealt with!!
 Report
Helpful?
Thank Digger1208
john s
2 reviews
“Hosts are nice enough, but.......”
Reviewed July 7, 2015

This property was beyond dated. To try and pass off the furnishings as "rustic" or "period" is just plain false advertising. The cabin, the appliances, the furnishings, all of it is worn out; carpets, upholstery, linens were all threadbare. I've stayed in some awful hotels, to include one in Niger, that hadn't seen any kind of update since the 60's;...
More
 Report
Helpful?
Thank john s
Marlene A
Hustonville, Kentucky
1 review
“In Town for the Rocky Mountain Irish Festival ”
Reviewed June 27, 2015 via mobile

Decided to attend the Rocky Mountain Irish Festival in Estes Park just three weeks before the event. I was needing an inexpensive and pet-friendly place for three of us. After much online searching, I came across the info for these cottages. I was able to rent cottage #8. It was just what we needed - a nice, clean place to...
More
 Report
Helpful?
Thank Marlene A
p n
Philadelphia, Pennsylvania
Level Contributor
3 reviews
2 helpful votes
“Everything I wanted”
Reviewed June 17, 2015

Here's what we got in Unit #7: Most important, terrific location. Five minutes to the Park entrance. Scenic river right at the back of the property. Estes Park is close enough but not too close. The unit: Spacious porch, an outdoor grill. Big bed, and sofa-bed. A skylight. Working fireplace. Baseboard heat for those chilly mornings. Tiny kitchen with everything...
More
 Report
Helpful?
1Thank p n
Ray R
Loveland, Colorado
Level Contributor
3 reviews
1 helpful vote
“Nice Getaway”
Reviewed May 31, 2015

Skyline is a peaceful relaxing experience. We have enjoyed it both as a couple and also with several friends. The hostess and host go out of their way to make us welcome. It is near the water so if we opened the window, we could hear the river lulling us to sleep. Skyline has grills and well-furnished kitchens. They have...
More
 Report
Helpful?
Thank Ray R
Joe S
1 review
“Beautiful Rustic Property @ the Base of Rocky Mountains”
Reviewed May 27, 2015

This is a beautiful location @ the base of the Rocky Mountain National Park. I don't think you can get much closer. Cottages were clean with full kitchens. Owners were very nice and we had a great time watching the wildlife across the stream. We cooked out and drank wine in the evening by the water. Excellent place for a...
More
 Report
Helpful?
Thank Joe S
Trish L
1 review
“Fishing Wildlife & Relaxation”
Reviewed May 27, 2015

Fantastic Romantic Getaway!!! We stayed in Cabin #5...views were incredible of the mountains and river. Very quiet with all the amenities...fishing...hiking...sun bathing...grilling...wildlife. Owners were great and Cabin was romantic and clean. Definitely the place to go and relax with nature.
 Report
Helpful?
Thank Trish L
Maren B
Level Contributor
4 reviews
2 helpful votes
“Not bad for the price, just don't expect 5 star resort”
Reviewed August 2, 2014 via mobile

We made a last minute decision to stay overnight in Estes, so this was available. We stayed in cabin 1, which was right next to the street. There was a little noise from traffic, but not too bad. Our dogs were allowed with an extra pet fee that was modest. I liked having a fireplace, especially as it rained during...
More
 Report
Helpful?
Thank Maren B
Jennifer L
Colorado Springs, Colorado
2 reviews
1 helpful vote
“Peaceful Rest from Busy World”
Reviewed August 1, 2014

My husband and I, as well as our 15 year old son, stayed in cabin #5 for 2 days last week (July), and we ALL loved it. It was rustic, so tho. a little older, lent a more relaxed atmosphere, and it was just above the river. We could open the windows, and hear the river throughout the cabin. I...
More
 Report
Helpful?
Thank Jennifer L
Jim C
Amarillo, Texas
1 review
1 helpful vote
“Had an awesome time!!”
Reviewed July 11, 2014

Larry,Sue & Brenda are marvelous always displayed outstanding customer service. We stayed in room #1 very clean.Towels, dishes propane, grill all provided.Thank you so much for a great, wonderful time

“Booked last minute for July 4th Getaway”
Reviewed July 7, 2014

My hubby and I stayed here 3 nights over the 4th of July weekend and it was one of the last cabins available. We booked this Cabin as we preferred the cabin feel vs a hotel. The photos on the website are very realistic and true. The items are all about 30 years old and we knew that going in when we choose to book it after researching it. We loved the following things about it: 1-It was very close to Rocky Mountain National Park, 2: It was cheaper like we wanted to pay because we knew we would only use it for sleeping and packing lunches, not eating there. 3. If you walk up the mountain in the back yard at about 5:30am, you will see the most beautiful sun rise. 4. If you are lucky, deer may greet you in the early morning. (See pictures) The unexpected cons were that I think cats have been in here before and if you are allergic, like my hubby and I are, we needed to take allergy pills for it. All in all we wore ourselves out hiking all day and slept like babies at night.

    Stayed July 2014, traveled as a couple
        Sleep Quality
        Rooms
        Service

Less
 Report
Helpful?
Thank Adventure_Seeker2121
Ask Adventure_Seeker2121 about Skyline Cottages
This review is the subjective opinion of a TripAdvisor member and not of TripAdvisor LLC.
Brenda W
Apache Junction, Arizona
2 reviews
1 helpful vote
“ENJOYED RUSTIC!”
Reviewed June 21, 2014

My Husband and I have stayed with Skyline Cottages 5 times and have always enjoyed our stay. We Love the rustic cabins, river walk, and welcoming atmosphere! The cabins are done in past era décor right down to the dishes! I did not want a hotel/motel/ritz feel! I wanted rustic and a river cabin experience and that's exactly what I got! Kudos for making it what it is! That is why we keep coming back.
Room Tip: Cabin 5 and 6 have wonderful Longs Peak and Big Thompson River Views!
See more room tips

    Stayed June 2014, traveled as a couple
        Value
        Location
        Sleep Quality
        Rooms
        Cleanliness
        Service

Less
 Report
Helpful?
Thank Brenda W
Ask Brenda W about Skyline Cottages
This review is the subjective opinion of a TripAdvisor member and not of TripAdvisor LLC.
John G
Holualoa, Hawaii, United States
Level Contributor
7 reviews
3 helpful votes
“Beyond Rustic”
Reviewed August 22, 2013

Recently stayed one night. This place is beyond rustic. Very small cabin. All contents have to more than 30 years old. Including the beds and sheets. Both sheets and towewls so thin you can see through them. Electricity won't even accomodate plugging in a laptop to be recharged. My wife got up during the night to use the restroom, turned on the lights and mice ran everywhere. She spent the rest of the night in the car. Racoons kept trying to get into the cabin during the night. If rustic and a return to the ancient past is what your looking for this is the place.

    Stayed August 2013, traveled as a couple
        Value
        Location
        Sleep Quality
        Rooms
        Cleanliness
        Service

Less
 Report
Helpful?
2Thank John G
See all 3 reviews by John G for Estes Park
Ask John G about Skyline Cottages
This review is the subjective opinion of a TripAdvisor member and not of TripAdvisor LLC.
Debbie M
Parkville, Missouri
Level Contributor
3 reviews
3 helpful votes
“Only place that was available and now I know why”
Reviewed August 7, 2013

I was not able to book our vacation until late may and will not make that mistake again. We like to stay at the ymca estes park but they could only accommodate us for 4 nights so we booked 4 more nights at skylines cottages. When making the reservation sue was very nice and answered all of my questions. Unfortunately the place is a dump. The entire property is in serious need of repair. We stayed in the only cabin/ house that had been built in 2004. Not sure if it was actually rehabbed in 2004 or newly built, Either way the job was not done right. It could have been ok but they choose to put furniture in it that is at least 30 years old, torn, stained and smelly and this is the best of the group. The pillows that I had to lay my head on we're disgusting, also stained and at least 30 years old. The entire contents of the cabin should be taken out and burned, nobody should use any of it. The sheets and towels are the same, old and disgusting. The sheets are so thin because they are that old. Everything in the kitchen was sticky. I truly believe we left the place cleaner than when we got there. What we got for the price was outragous. I do not have anything good to say about the place other than don't go.
Room Tip: There are no good rooms here!
See more room tips

    Stayed August 2013, traveled with family
        Value
        Location
        Sleep Quality
        Rooms
        Cleanliness
        Service

Less
 Report
Helpful?
3Thank Debbie M
Ask Debbie M about Skyline Cottages
This review is the subjective opinion of a TripAdvisor member and not of TripAdvisor LLC.
Erin M
Philadelphia, Pennsylvania
2 reviews
1 helpful vote
“Homey feel, practically adjacent to park”
Reviewed July 10, 2013

We just stayed for three days in one of the smaller cabins here. We were looking for a cabin run with a ma and pa feel, and that's what we got. Our cottage was adorable; we found the decor charming. I recognized a few items from my childhood in the 80s. Sue, the proprietor, is adorable and affable. There is a ton of shared real estate on the patios - one is more of a raised deck and the other is down by the river. We could gaze at the snow caps while eating breakfast in our kitchen. But the best part of the cottages? They are one of the closest properties to the Rocky Mountain National Park. We will definitely stay here again on our next visit to Estes Park.
Room Tip: Call Sue and she will help you figure out which of the cottages is the right fit.
See more room tips

    Stayed July 2013, traveled with family
        Value
        Location
        Sleep Quality
        Rooms
        Cleanliness
        Service

Less
 Report
Helpful?
Thank Erin M
Ask Erin M about Skyline Cottages
This review is the subjective opinion of a TripAdvisor member and not of TripAdvisor LLC.
BabsB199
Seattle, Washington
1 review
“Great Trip!!”
Reviewed April 3, 2013

I came here with my fiance and we had a great time. We live in a big city so it was nice to get away from all that and just enjoy some nature. The cabins are older but are still very nice. The service was great. Sue helped us with any thing that we needed. We had no problems there. I would recommend skyline to anyone!! Loved my stay here!

    Stayed August 2012, traveled as a couple
        Value
        Location
        Sleep Quality
        Rooms
        Cleanliness
        Service

Less
 Report
Helpful?
Thank BabsB199
Ask BabsB199 about Skyline Cottages
This review is the subjective opinion of a TripAdvisor member and not of TripAdvisor LLC.
HBaggs
Las Vegas, Nevada
1 review
“A great city getaway.”
Reviewed March 17, 2013

Originally being from the NW, I found this place to be very comfortable. The view is amazing, the cottages are clean, and the management was very punctual with their help. There is a stream that runs on the edge of the property that you can fish from too! I would recommend this place to anyone who wants to experience what a beautiful area like Estes Park has to offer, while having a comfortable place to stay.

    Stayed June 2012, traveled with friends
        Value
        Location
        Sleep Quality
        Rooms
        Cleanliness
        Service

Less
 Report
Helpful?
Thank HBaggs
Ask HBaggs about Skyline Cottages
This review is the subjective opinion of a TripAdvisor member and not of TripAdvisor LLC.
Larry C
Henderson, Nevada
1 review
1 helpful vote
“Beautiful, Clean, Great View!!”
Reviewed September 3, 2012

My family and I have been staying at Skyline Cottages every year for the last 4 years for 7 to 10
days every year. All of the cabins are old rustic cabins, extremely clean and well maintained. They
are located by the river and have a gorgeous river walk and and a fantastic view of the mountains.
The management ALWAYS took care of any and all requests I ever had. I have read some of the
other reviews on this site and have a VERY, VERY hard time believing the ones that gave a bad review, especially the person who said they would not get a receipt. I have ALWAYS gotten a receipt from the management without asking. All of the cabins have all of the comforts of home and the
management always treated us as if we were family. Like I said above these are rustic cabins, we
are not talking about the Hilton, If that is what you are looking for and stay at Skyline then don't
complain about it, go stay at the Hilton.

    Stayed August 2012, traveled with family
        Value
        Location
        Sleep Quality
        Rooms
        Cleanliness
        Service

Less
 Report
Helpful?
1Thank Larry C
Ask Larry C about Skyline Cottages
This review is the subjective opinion of a TripAdvisor member and not of TripAdvisor LLC.
William H
Broomfield, Colorado
1 review
2 helpful votes
“Terrible place to stay”
Reviewed August 21, 2012

This is not a nice place. The facility is desperately in need of repair and updating. Electrical and plumbing is so bad that I don't think it's safe. Our shower flooded when my wife took a shower. I told the lady who operates it and she got mad at us because she needed to go somewhere and didn't have Tim for it. I would never recommend this place. There are much better places in Estes Park.

    Stayed June 2012, traveled with family
        Value
        Location
        Sleep Quality
        Rooms
        Cleanliness
        Service

Less
 Report
Helpful?
2Thank William H
Ask William H about Skyline Cottages
This review is the subjective opinion of a TripAdvisor member and not of TripAdvisor LLC.
sue l, Owner at Skyline Cottages, responded to this review
I am the owner/manager of Skyline Cottages and as I was leaving the property to go to Mass the customer came to the office and stated that the shower would not drain properly. To immediately solve the problem I upgraded him to cottage #3, The Southwest Spa which was three times as large and twice as expensive as the one he was in so that they could continue there stay with little and/or no interruption. They moved into said cottage, used the shower, cooked breakfast and were in it for 5 hours. At approximately 2:00 pm he came to the office and said they were leaving and wanted a refund. I stated that there would not be a refund as check out time was 10:00 am. He left the property around 3:00 pm and then canceled his credit card charge. The credit card company backed me up and said the charges were valid. He then proceeded to trash Skyline Cottages through Trip Advisor for revenge.

Sue Lamb, Owner/Manager
Report response as inappropriate
This response is the subjective opinion of the management representative and not of TripAdvisor LLC.
Amykate468
Arvada, Colorado, United States
2 reviews
“Well kept, beautiful cabin”
Reviewed June 18, 2012

My husband, two teenaged sons, and two dogs stayed in Cabin 3 (Southwest Spa) for 9 days and it was wonderful! The place is clean, comfortable and quiet, and had everything we needed. If you're looking for the newest technology, this isn't the place for you (plenty of TV's, but not the new models), but if you want a quiet and clean place to stay, this is an excellent choice. The owner, Sue, was wonderful - everything we needed was available, and she has so much character, too! We plan on staying here anytime we come again in the future.

    Stayed June 2012, traveled with family
        Value
        Location
        Sleep Quality
        Rooms
        Cleanliness
        Service

Less
 Report
Helpful?
Thank Amykate468
Ask Amykate468 about Skyline Cottages
This review is the subjective opinion of a TripAdvisor me

“Clean, comfortable, great view, good location”
Reviewed April 23, 2012

I've been staying a week to 10 days at Skyline Cottages almost every summer since 1971. The cabins and cottages, are clean, comfortable, equipped for cooking and pet friendly. The location on the Big Thompson River is excellent and there is a family-sized deck overlooking the river and an opportunity to fish. Sue owns the place and is affable, helpful...
More
 Report
Helpful?
1Thank Bill H
Beth H
Northbrook, Illinois
Level Contributor
46 reviews
8 hotel reviews
26 helpful votes
“Family tradition in Estes”
Reviewed February 29, 2012

We have been going to Skyline Cottages for years and have enjoyed it as a family-friendly, homely set of cottages at a terrific location. Click around on the website to view what the rooms each look like (obviously the spa-marked rooms are a little nicer), but don't expect 5-star class, expect 5-star comfort. This is an old-fashioned and relaxing getaway...
More
 Report
Helpful?
Thank Beth H
Tamara53
Silverthorne, Colorado
Level Contributor
3 reviews
1 helpful vote
“OK accomodations but terrible customer service”
Reviewed July 31, 2011

The cottage was nice. Comfortable beds, outdated pillows, clean, well equipped cottage. It's great that it was pet friendly. Unfortunately the management is horrible, and don't stay here if you'll be needing a business receipt. The owner won't give you one. If you're traveling on business stay elsewhere.
 Report
Helpful?
1Thank Tamara53
Emily Kalah G
London, United Kingdom
Level Contributor
4 reviews
4 hotel reviews
2 helpful votes
“Cosy and suitable - great view”
Reviewed September 27, 2010

was dubious after reading reviews on this site, but everywhere else was booked so decided to give it a go. was pleasantly surprised! great view of the diamond of longs peak out the window, quite, by the stream... room was nice (not modern, but clean, well equipped and comfortable).
 Report
Helpful?
1Thank Emily Kalah G
Glaber
1 review
1 helpful vote
“Dilopadated and Dirty, what a dump”
Reviewed August 2, 2010

This has got to be one of the worst places in Eates Park! Takey advise and stay somewhere else!! The cabins are in dire need of fixing, there are no batteries in the smoke detectors and the water in the kitchen sink runs from both directions so you don't know which way shuts the faucet off!! The window in the...
More
 Report
Helpful?
1Thank Glaber
PeakTraveler
Colorado Springs
Level Contributor
5 reviews
4 hotel reviews
7 helpful votes
“Shabby & Overpriced---Vacancies for a Reason!”
Reviewed June 21, 2010

My husband and I stayed at the Skyline because it was the only lodging with vacancies close to where our family was staying at the YMCA camp. It was a very convenient location. Honestly, I wouldn't have minded the condition--for half the price. We stayed in cabin #1, right next to the highway. It was very old in every way,...
More
 Report
Helpful?
1Thank PeakTraveler
monkster27
Milford, Pennsylvania
Level Contributor
25 reviews
12 hotel reviews
9 helpful votes
“Could use some updating”
Reviewed June 17, 2010

The owner Sue was very pleasant and as we stayed in the North cabin on the hill , 1/4 mile away ,she actually led us up there and took us around the cabin. At first glance we weren't totally repulsed and the deck looked perfect for bird watching and safe for our little dogs to play. We saw right away...
More
 Report
Helpful?
1Thank monkster27
EstesCo
CO
1 review
1 helpful vote
“AMAZING place! Would recommend this place to anyone!”
Reviewed September 18, 2009

Skyline is a quaint, very well-maintained, immaculate set of cottages along the river in Estes Park, CO. The cottages are pricture-perfect. Excellent mattresses for those with bad backs. Clean site so that our young child could play safely. Would recommend Skyline Cottages, their Owner and staff to anyone. Book in advance as they fill up and are not open year...
More
 Report
Helpful?
1Thank EstesCo
justfunforall
Texas
1 review
“Great place, very relaxing”
Reviewed September 17, 2009

My daughter and I had a great time, just like staying in a cabin anywhere. Nothing fancy, but nice beds, great views and comfortable surroundings. We found the cabin and the outdoor area clean and well kept. I would recommend the cabins, if you don't need a five star. It is a great place to hang your hat at night.
 Report
Helpful?
Thank justfunforall
MountainLover42
Oklahoma
2 reviews
“Fabulous Trip”
Reviewed September 13, 2009

I read the reviews after I booked the cabin and was a little nervous. I was very pleasantly surprised and wondered where the other people were staying that hated it so much. We stayed in Cabin #2. It was very clean. The bathroom was huge and clean. The spa was in a seperate area off the bathroom also very clean....
More
 Report
Helpful?
Thank MountainLover42
Previous
Next

“Worst travel experience ever!”
Reviewed August 23, 2009

God, I wish I had seen this website before I was defrauded out of $405 ! Skyline Cottages has photos of their rooms and outdoor areas on their website that are at least 30 years old, and there is now virtually NO UPKEEP performed on the property, inside or out! The owner DEMANDED FULL PAYMENT for the 3 nights we...
More
 Report
Helpful?
2Thank Colorado_Sailor36
Krisrocks
Detroit
1 review
“What a fabulous place on the Big Thompson River with spectacular views!”
Reviewed July 30, 2009

We stayed for six nights in a quaint, clean cottage with all the amenities. Our host Sue was so hospitable and sweet.! By far the best thing this wonderful little resort has going for it is the fantastic location and fabulous scenery. The sounds and sights of a running Rocky Mountain river with towering peaks in the background and lush...
More
 Report
Helpful?
Thank Krisrocks
kltjrt
Houston, Tx
1 review
1 helpful vote
“Great location and Wireless Internet, that was the only positive.”
Reviewed July 20, 2009

We stayed in the Western Spa #7. No privacy. Unit was right next to the street. You could also hear your neighbor on what they were having for breakfast. Everything was old. They had better silverware at the Alpine visitor center. The towels and sheets were very rough. The cheapest towels at Walmart are softer. The TV was from the...
More
 Report
Helpful?
1Thank kltjrt
fiddlerdi
Topeka Kansas
1 review
“We really liked this place”
Reviewed July 6, 2009

If you are used to luxury this is not your kind of place. If you want to have a decent place to stay out of the crowds and chaos of Estes Park stay at the Skyline north cabin. It is old fashioned. I don't know about the main cabins as we stayed up the road about 1/4 mile. The view...
More
 Report
Helpful?
Thank fiddlerdi
65Mustangman
Topeka, Kansas
Level Contributor
101 reviews
21 hotel reviews
37 helpful votes
“This is a TERRIBLE PLACE”
Reviewed July 5, 2009

We wish we had read these reviews before we reserved a room. The property was in horrible condition compared to the photos on the internet. When making the reservations on the phone we were told our room had a view of the mountains and a road. The mountains' view was okay but the road was practically outside our door. We...
More
 Report
Helpful?
1Thank 65Mustangman
sunnyd6
Colorado
1 review
“been to better, but not horrible”
Reviewed June 10, 2009

We stayed a cabin about 1/4 mile away that backed up to RMNP but was under the Skyline Cottage mgt. Cabin was equipped but did smell of animals, animal hair on furniture, needs to be updated and the yard for the dog was a joke... but we had heat, elec, a roof over our head and a hot shower. I...
More
 Report
Helpful?
Thank sunnyd6
angeldoll60
Phoenix, Az
1 review
“Best place to stay for your money and Beautiful also!”
Reviewed April 29, 2009

Skyline Cottages in Estes Park was the best vacation I have had in years. This charming rustic cottage lodge provided all the comforts of home and some of the things I wish I could have packaged to take back with me! Skyline cottages name says it all , it is located on the skyline of the beautiful Rocky Mountains. This...
More
 Report
Helpful?
Thank angeldoll60
goldie8
Denver
1 review
1 helpful vote
“What a [--]”
Reviewed September 12, 2008

Absolutely horrible. We booked this place based on the web site that made it look pretty good. Not the case. Dirty old and worn out. The carpet was dirty and well past it's useful life. The walls had been patched badly. The entire property was not well kept and we were told that our unit was on the river. Not...
More
 Report
Helpful?
1Thank goldie8
freeburgmom
Freeburg, IL
2 reviews
2 helpful votes
“The armpit of Estes Park”
Reviewed August 29, 2008

We weren't expecting much after reading the majority of reviews posted here, but we planned this trip on short notice and we were desperate. This was the only place available, and now I know why. The rooms were straight out of 1972, and so was the dust covering everything in them. Ceilings so low you had to watch yourself or...
More
 Report
Helpful?
2Thank freeburgmom
austintx001
austin, tx
1 review
“Treated like family”
Reviewed August 21, 2008

My son and I ended a 5 day backcountry trip at RMNP 2 days early because of complications. We had a reservation after our trip was supposed to end, but the proprietors of the establishment accomodated us without any hesitation whatsoever! We had no vehicle during our stay and the new soon to be owner, Kelly, was so kind to...
More
 Report
Helpful?
Thank austintx001

“Great location, but don't stay in #4”
Reviewed August 20, 2008

We stayed in #4. We booked 3 nights and only stayed 2. We left early even though we paid for the 3rd night. It was that bad. First thing I noticed on entering was a horrible smell coming from the kitchen area. Then it only had 1/4 a roll of toilet paper in the entire place. And both mornings we...
More
 Report
Helpful?
1Thank Nazzery
rockyresident
denver, colorado
1 review
“A Unique Place to Stay”
Reviewed December 12, 2007

These are not your sterile cookie cutter cottages. They are homey and very pet friendly. The view from the property is unmatched and the river/patio area is fabulous. We found the cottage to be clean and fully equipped for cooking. The owner is fun and loves animals!!
 Report
Helpful?
Thank rockyresident
BeauTater
Colorado
1 review
1 helpful vote
“Ew.”
Reviewed October 11, 2007

What a complete dump.
 Report
Helpful?
1Thank BeauTater
Sunraindancer
Houston, Texas
Level Contributor
110 reviews
12 hotel reviews
57 helpful votes
“Location, Location, Location”
Reviewed September 23, 2007

This property is in a good location. You can bring your pets.
HOWEVER, it is old, old, and overpriced. We had "Cabin" #5. It has a deck, a view of the river, and a view of the mountains. The owner is never there. We arrived on a Sunday around 2:15 PM. She was not there. We came back at 3:00 PM, she was not there. We came back at 3:45 PM and she was not there but there was a note on a chalkboard dated 3:30 PM that she was not there and we could go to our cabin. We finally left at 5:30 PM to go and eat hoping that we could get back in with no key. The cabins are all old except for the new one, #3. Ours, #5, is makeshift and is very old. Read the other reviews of this property first. I do not expect that these cabins will be there much longer as development is about to overtake this area with new condos and duplexes. My recomendation is go elsewhere.
Stayed September 2007
Less
 Report
Helpful?
1Thank Sunraindancer
See all 7 reviews by Sunraindancer for Estes Park
Ask Sunraindancer about Skyline Cottages
This review is the subjective opinion of a TripAdvisor member and not of TripAdvisor LLC.
estesrester
co
1 review
1 helpful vote
“Unbelievably RUDE”
Reviewed August 29, 2007

The owner never stated that there would be a cancellation fee after I asked about it. She charged me when I tried to cancel 3 days in advance. Nowhere on the Website does it talk about a fee, and I asked when I booked if my card would be charged and she said only if I don't show up. When I reminded her of that, she said "so- I don't have to tell you about it. It's stated in my office, and that's all I'm required to do." Can't believe that there are still businesses so desparate that they have to stoop to this level.

    Stayed August 2007, traveled with family
        Value
        Service
        Business service (e.g., internet access)

Less
 Report
Helpful?
1Thank estesrester
Ask estesrester about Skyline Cottages
This review is the subjective opinion of a TripAdvisor member and not of TripAdvisor LLC.
LasVegasMegan
las vegas
1 review
1 helpful vote
“Great Experience staying at Skyline”
Reviewed July 1, 2007

My stay at Skyline Was absolutely wonderful. The cottages were so immaculant and clean. We had a wonderful stay. Suzi the owner was so pleasant and sweet and we would definitely stay at her cottages again. Megan Sutton Las Vegas, Nevada
 Report
Helpful?
1Thank LasVegasMegan
hilltopDenver
Denver
1 review
2 helpful votes
“Great Location, Pet Friendly, Rustic Cabins”
Reviewed June 28, 2007

Great location, pet friendly, rustic experience! We stayed at Skyline and had a wonderful time. We loved the fact that we could bring our beloved pet dog with no probs whatsoever. Rooms were clean, management cooperative and an overall enjoyable experience. Definitely will stay again next year!
 Report
Helpful?
2Thank hilltopDenver
jrbosko
colorado springs
1 review
2 helpful votes
“You gotta be kiddin' me!!!”
Reviewed June 25, 2007

Don't stay here! The website is SOOO inaccurate. The place is DIRTY, HOT, HOT, HOT! My watch said the room was 102 degrees! We found a mouse poison box under the sink in the bedroom, our dog could have gotten to it if we hadn't found it first. The kitchen looks about 50 years old, the toilet didn't work, the manager said it was just "slow". The wood on the deck is rotting and covered with astroturf. Dont fall through! Our room even had an exposed water heater sitting next to the fridge. For $180 a night, I think they could have put in an air conditioner in the window! We got some of our money back, but they kept the deposit of course!
Stayed June 2007
Less
 Report
Helpful?
2Thank jrbosko
Ask jrbosko about Skyline Cottages
This review is the subjective opinion of a TripAdvisor member and not of TripAdvisor LLC.
noinenlotne
Richmond, VA
1 review
2 helpful votes
“Dirty rooms and unresponsive ownership/management”
Reviewed August 14, 2006

Let me be succinct. The rooms are not clean - the River Cabin reeked of cat urine and had hair on the sheets. The shams were moldy and when we brought this to the owner's attention, she told us "But you are not supposed to sleep on the shams!'. The Western Spa's bed sheets were covered in human hair and the pull out sofa's sheets had food all over them - and the owner blamed US for not having changed the sheets. We moved out after one miserable night - NEVER to return.

    Liked — nothing
    Disliked — everything
    Tips/Secrets — do NOT stay here

    Stayed July 2006, traveled with family
        Value
        Location
        Check in / front desk

Less
 Report
Helpful?
2Thank noinenlotne
Ask noinenlotne about Skyline Cottages
This review is the subjective opinion of a TripAdvisor member and not of TripAdvisor LLC.
maryBTucson_AZUSA
Tucson, AZ USA
Level Contributor
3 reviews
3 hotel reviews
15 helpful votes
“What a dive!”
Reviewed June 9, 2006

Although the location is nice (right on the Big Thompson river and close to the entrance to RMNP), the cottages themselves are cramped and ugly. We were very disappointed - for the price I think we could have done better. Our cottage consisted of one room, (in a triplex unit) with a uncomfortable daybed, an old dirty armchair, ugly grey carpet, a miniscule kitchenette with a sink, refrig, stove, small microwave and a tiny kitchen table that rocked on uneven legs, a relatively comfortable queen bed next to a fireplace, a bathroom with a door that wouldn't latch, and a tiny shower. It came equipped with mismatched plates, miscellaneous silverware, and assorted old pots and pans. Also, there was no air conditioning, and there was a heat wave the week we were there, so the cottage was too hot to stay in comfortably during the afternoon if one wanted a nap or something. There were also outside grills.

On the "plus" side: location, location, location! There was a deck right down on the river that was very nice to sit on, and an upper deck that had a terrific view of the mountains. There are expensive resorts going up on either side of the place, so I think this place may not be here much longer. In summary, you are paying for the location, but if you care about the quality of the room this is not satisfactory. If this had been less expensive it might have been okay, but it is comparably priced to much nicer places. We paid $600 for 5 nights, in the first week of June. Estes Park is lovely, though, so we will be back - just not here!