// Generated by CoffeeScript 1.12.2
(function() {
  var Credit,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Credit = (function() {
    module.exports = Credit;

    window.Credit = Credit;

    Credit.defaultFormat = /(\d{1,4})/g;

    function Credit() {
      this.restrictCVC = bind(this.restrictCVC, this);
      this.restrictExpiry = bind(this.restrictExpiry, this);
      this.restrictCardNumber = bind(this.restrictCardNumber, this);
      this.restrictNumeric = bind(this.restrictNumeric, this);
      this.reFormatCVC = bind(this.reFormatCVC, this);
      this.formatBackExpiry = bind(this.formatBackExpiry, this);
      this.formatForwardSlashAndSpace = bind(this.formatForwardSlashAndSpace, this);
      this.formatForwardExpiry = bind(this.formatForwardExpiry, this);
      this.formatCardExpiry = bind(this.formatCardExpiry, this);
      this.reFormatExpiry = bind(this.reFormatExpiry, this);
      this.formatBackCardNumber = bind(this.formatBackCardNumber, this);
      this.formatCardNumber = bind(this.formatCardNumber, this);
      this.reFormatCardNumber = bind(this.reFormatCardNumber, this);
      this.fieldStatus = bind(this.fieldStatus, this);
    }

    Credit.prototype.init = function(numId, expId, cvcId, subId, typId, resId) {
      var cvc, exp, num, res, sub, typ, updateType, validate;
      num = document.getElementById(numId);
      exp = document.getElementById(expId);
      cvc = document.getElementById(cvcId);
      sub = document.getElementById(subId);
      typ = document.getElementById(subId);
      res = document.getElementById(resId);
      this.cardNumberInput(num);
      this.expiryInput(exp);
      this.cvcInput(cvc);
      updateType = (function(_this) {
        return function(e) {
          var cardType, msg;
          cardType = _this.parseCardType(e.target.value);
          msg = cardType || 'invalid';
          typ.innerHTML = msg;
          Util.log('Credit.init() updateType', num.value, exp.value, cvc.value, msg);
        };
      })(this);
      num.addEventListener('input', updateType);
      validate = (function(_this) {
        return function(e) {
          var expiryObj, msg, valid;
          Util.noop(e);
          valid = [];
          expiryObj = _this.parseCardExpiry(exp.value);
          valid.push(_this.fieldStatus(num, _this.validateCardNumber(num.value)));
          valid.push(_this.fieldStatus(exp, _this.validateCardExpiry(expiryObj)));
          valid.push(_this.fieldStatus(cvc, _this.validateCardCVC(cvc.value, typ.innerHTML)));
          msg = valid.every(Boolean) ? 'valid' : 'invalid';
          res.innerHTML = msg;
          Util.log('Credit.init() validate', num.value, exp.value, cvc.value, msg);
        };
      })(this);
      return sub.addEventListener('click', validate);
    };

    Credit.prototype.fieldStatus = function(input, valid) {
      if (valid) {
        this.removeClass(input.parentNode, 'error');
      } else {
        this.addClass(input.parentNode, 'error');
      }
      return valid;
    };

    Credit.prototype.addClass = function(elem, klass) {
      if (elem.className.indexOf(klass) === -1) {
        elem.className += ' ' + klass;
      }
    };

    Credit.prototype.removeClass = function(elem, klass) {
      if (elem.className.indexOf(klass) !== -1) {
        elem.className = elem.className.replace(klass, '');
      }
    };

    Credit.prototype.cardFromNumber = function(num) {
      var card, i, len, ref, ven;
      num = (num + '').replace(/\D/g, '');
      ven = {};
      ref = Credit.cards;
      for (i = 0, len = ref.length; i < len; i++) {
        card = ref[i];
        if (!(card.pattern.test(num))) {
          continue;
        }
        ven = card;
        break;
      }
      return ven;
    };

    Credit.prototype.cardFromType = function(type) {
      var card, i, len, ref, ven;
      ven = {};
      ref = Credit.cards;
      for (i = 0, len = ref.length; i < len; i++) {
        card = ref[i];
        if (!(card.type === type)) {
          continue;
        }
        ven = card;
        break;
      }
      return ven;
    };

    Credit.prototype.getCaretPos = function(ele) {
      var r, rc, re;
      if (ele.selectionStart != null) {
        return ele.selectionStart;
      } else if (document.selection != null) {
        ele.focus();
        r = document.selection.createRange();
        re = ele.createTextRange();
        rc = re.duplicate();
        re.moveToBookmark(r.getBookmark());
        rc.setEndPoint('EndToStart', re);
        return rc.text.length;
      }
    };

    Credit.prototype.eventNormalize = function(listener) {
      return function(e) {
        if (e == null) {
          e = window.event;
        }
        e.target = e.target || e.srcElement;
        e.which = e.which || e.keyCode;
        if (e.preventDefault == null) {
          e.preventDefault = function() {
            return this.returnValue = false;
          };
        }
        return listener(e);
      };
    };

    Credit.prototype.listen = function(ele, event, listener) {
      listener = this.eventNormalize(listener);
      if (ele.addEventListener != null) {
        return ele.addEventListener(event, listener, false);
      } else {
        return ele.attachEvent("on" + event, listener);
      }
    };

    Credit.cards = [
      {
        type: 'visaelectron',
        pattern: /^4(026|17500|405|508|844|91[37])/,
        format: Credit.defaultFormat,
        length: [16],
        cvcLength: [3],
        luhn: true
      }, {
        type: 'maestro',
        pattern: /^(5(018|0[23]|[68])|6(39|7))/,
        format: Credit.defaultFormat,
        length: [12, 13, 14, 15, 16, 17, 18, 19],
        cvcLength: [3],
        luhn: true
      }, {
        type: 'forbrugsforeningen',
        pattern: /^600/,
        format: Credit.defaultFormat,
        length: [16],
        cvcLength: [3],
        luhn: true
      }, {
        type: 'dankort',
        pattern: /^5019/,
        format: Credit.defaultFormat,
        length: [16],
        cvcLength: [3],
        luhn: true
      }, {
        type: 'visa',
        pattern: /^4/,
        format: Credit.defaultFormat,
        length: [13, 16],
        cvcLength: [3],
        luhn: true
      }, {
        type: 'mastercard',
        pattern: /^(5[1-5]|2[2-7])/,
        format: Credit.defaultFormat,
        length: [16],
        cvcLength: [3],
        luhn: true
      }, {
        type: 'amex',
        pattern: /^3[47]/,
        format: /(\d{1,4})(\d{1,6})?(\d{1,5})?/,
        length: [15],
        cvcLength: [3, 4],
        luhn: true
      }, {
        type: 'dinersclub',
        pattern: /^3[0689]/,
        format: /(\d{1,4})(\d{1,4})?(\d{1,4})?(\d{1,2})?/,
        length: [14],
        cvcLength: [3],
        luhn: true
      }, {
        type: 'discover',
        pattern: /^6([045]|22)/,
        format: Credit.defaultFormat,
        length: [16],
        cvcLength: [3],
        luhn: true
      }, {
        type: 'unionpay',
        pattern: /^(62|88)/,
        format: Credit.defaultFormat,
        length: [16, 17, 18, 19],
        cvcLength: [3],
        luhn: false
      }, {
        type: 'jcb',
        pattern: /^35/,
        format: Credit.defaultFormat,
        length: [16],
        cvcLength: [3],
        luhn: true
      }
    ];

    Credit.prototype.luhnCheck = function(num) {
      var digit, digits, i, len, odd, sum;
      odd = true;
      sum = 0;
      digits = (num + '').split('').reverse();
      for (i = 0, len = digits.length; i < len; i++) {
        digit = digits[i];
        digit = parseInt(digit, 10);
        if ((odd = !odd)) {
          digit *= 2;
        }
        if (digit > 9) {
          digit -= 9;
        }
        sum += digit;
      }
      return sum % 10 === 0;
    };

    Credit.prototype.hasTextSelected = function(target) {
      var ref;
      if ((typeof document !== "undefined" && document !== null ? (ref = document.selection) != null ? ref.createRange : void 0 : void 0) != null) {
        if (document.selection.createRange().text) {
          return true;
        }
      }
      return (target.selectionStart != null) && target.selectionStart !== target.selectionEnd;
    };

    Credit.prototype.replaceFullWidthChars = function(str) {
      var char, chars, fullWidth, halfWidth, i, idx, len, value;
      if (str == null) {
        str = "";
      }
      fullWidth = '\uff10\uff11\uff12\uff13\uff14\uff15\uff16\uff17\uff18\uff19';
      halfWidth = '0123456789';
      value = '';
      chars = Util.isStr(str) ? str.split('') : [];
      for (i = 0, len = chars.length; i < len; i++) {
        char = chars[i];
        idx = fullWidth.indexOf(char);
        if (idx > -1) {
          char = halfWidth[idx];
        }
        value += char;
      }
      return value;
    };

    Credit.prototype.reFormatCardNumber = function(e) {
      var cursor;
      cursor = this.getCaretPos(e.target);
      e.target.value = this.formatCardNumber(e.target.value);
      if ((cursor != null) && e.type !== 'change') {
        return e.target.setSelectionRange(cursor, cursor);
      }
    };

    Credit.prototype.formatCardNumber = function(e) {
      var card, cursor, digit, fn, length, re, upperLength, value;
      digit = String.fromCharCode(e.which);
      if (!/^\d+$/.test(digit)) {
        return;
      }
      value = e.target.value;
      card = this.cardFromNumber(value + digit);
      length = (value.replace(/\D/g, '') + digit).length;
      upperLength = 16;
      if (card) {
        upperLength = card.length[card.length.length - 1];
      }
      if (length >= upperLength) {
        return;
      }
      cursor = this.getCaretPos(e.target);
      if (cursor && cursor !== value.length) {
        return;
      }
      if (card && card.type === 'amex') {
        re = /^(\d{4}|\d{4}\s\d{6})$/;
      } else {
        re = /(?:^|\s)(\d{4})$/;
      }
      fn = function() {
        return e.target.value = value + " " + digit;
      };
      if (re.test(value)) {
        e.preventDefault();
        return setTimeout(fn, 1000);
      } else if (re.test(value + digit)) {
        e.preventDefault();
        return setTimeout(fn, 1000);
      }
    };

    Credit.prototype.formatBackCardNumber = function(e) {
      var cursor, fn, value;
      value = e.target.value;
      if (e.which !== 8) {
        return;
      }
      cursor = this.getCaretPos(e.target);
      if (cursor && cursor !== value.length) {
        return;
      }
      if (/\d\s$/.test(value)) {
        e.preventDefault();
        fn = function() {
          return e.target.value = value.replace(/\d\s$/, '');
        };
        return setTimeout(fn, 1000);
      } else if (/\s\d?$/.test(value)) {
        e.preventDefault();
        fn = function() {
          return e.target.value = value.replace(/\d$/, '');
        };
        return setTimeout(fn, 1000);
      }
    };

    Credit.prototype.reFormatExpiry = function(e) {
      var cursor;
      cursor = this.getCaretPos(e.target);
      e.target.value = this.formatCardExpiry(e.target.value);
      if ((cursor != null) && e.type !== 'change') {
        return e.target.setSelectionRange(cursor, cursor);
      }
    };

    Credit.prototype.formatCardExpiry = function(e) {
      var digit, fn, val;
      digit = String.fromCharCode(e.which);
      if (!/^\d+$/.test(digit)) {
        return;
      }
      val = e.target.value + digit;
      fn = function() {
        return e.target.value = "0" + val + " / ";
      };
      if (/^\d$/.test(val) && (val !== '0' && val !== '1')) {
        e.preventDefault();
        return setTimeout(fn, 1000);
      } else if (/^\d\d$/.test(val)) {
        e.preventDefault();
        return setTimeout(fn, 1000);
      }
    };

    Credit.prototype.formatForwardExpiry = function(e) {
      var digit, val;
      digit = String.fromCharCode(e.which);
      if (!/^\d+$/.test(digit)) {
        return;
      }
      val = e.target.value;
      if (/^\d\d$/.test(val)) {
        return e.target.value = val + " / ";
      }
    };

    Credit.prototype.formatForwardSlashAndSpace = function(e) {
      var val, which;
      which = String.fromCharCode(e.which);
      if (!(which === '/' || which === ' ')) {
        return;
      }
      val = e.target.value;
      if (/^\d$/.test(val) && val !== '0') {
        return e.target.value = "0" + val + " / ";
      }
    };

    Credit.prototype.formatBackExpiry = function(e) {
      var cursor, fn, value;
      value = e.target.value;
      if (e.which !== 8) {
        return;
      }
      cursor = this.getCaretPos(e.target);
      if (cursor && cursor !== value.length) {
        return;
      }
      if (/\d\s\/\s$/.test(value)) {
        e.preventDefault();
        fn = function() {
          return e.target.value = value.replace(/\d\s\/\s$/, '');
        };
        return setTimeout(fn, 1000);
      }
    };

    Credit.prototype.reFormatCVC = function(e) {
      var cursor;
      cursor = this.getCaretPos(e.target);
      e.target.value = this.replaceFullWidthChars(e.target.value).replace(/\D/g, '').slice(0, 4);
      if ((cursor != null) && e.type !== 'change') {
        return e.target.setSelectionRange(cursor, cursor);
      }
    };

    Credit.prototype.restrictNumeric = function(e) {
      var input;
      if (e.metaKey || e.ctrlKey) {
        return;
      }
      if (e.which === 0) {
        return;
      }
      if (e.which < 33) {
        return;
      }
      input = String.fromCharCode(e.which);
      if (!/^\d+$/.test(input)) {
        return e.preventDefault();
      }
    };

    Credit.prototype.restrictCardNumber = function(e) {
      var card, digit, value;
      digit = String.fromCharCode(e.which);
      if (!/^\d+$/.test(digit)) {
        return;
      }
      if (this.hasTextSelected(e.target)) {
        return;
      }
      value = (e.target.value + digit).replace(/\D/g, '');
      card = this.cardFromNumber(value);
      if (card && value.length > card.length[card.length.length - 1]) {
        return e.preventDefault();
      } else if (value.length > 16) {
        return e.preventDefault();
      }
    };

    Credit.prototype.restrictExpiry = function(e) {
      var digit, value;
      digit = String.fromCharCode(e.which);
      if (!/^\d+$/.test(digit)) {
        return;
      }
      if (this.hasTextSelected(e.target)) {
        return;
      }
      value = e.target.value + digit;
      value = value.replace(/\D/g, '');
      if (value.length > 6) {
        return e.preventDefault();
      }
    };

    Credit.prototype.restrictCVC = function(e) {
      var digit, val;
      digit = String.fromCharCode(e.which);
      if (!/^\d+$/.test(digit)) {
        return;
      }
      if (this.hasTextSelected(e.target)) {
        return;
      }
      val = e.target.value + digit;
      if (val.length > 4) {
        return e.preventDefault();
      }
    };

    Credit.prototype.cvcInput = function(input) {
      this.listen(input, 'keypress', this.restrictNumeric);
      this.listen(input, 'keypress', this.restrictCVC);
      this.listen(input, 'paste', this.reFormatCVC);
      this.listen(input, 'change', this.reFormatCVC);
      return this.listen(input, 'input', this.reFormatCVC);
    };

    Credit.prototype.expiryInput = function(input) {
      this.listen(input, 'keypress', this.restrictNumeric);
      this.listen(input, 'keypress', this.restrictExpiry);
      this.listen(input, 'keypress', this.formatCardExpiry);
      this.listen(input, 'keypress', this.formatForwardSlashAndSpace);
      this.listen(input, 'keypress', this.formatForwardExpiry);
      this.listen(input, 'keydown', this.formatBackExpiry);
      this.listen(input, 'change', this.reFormatExpiry);
      return this.listen(input, 'input', this.reFormatExpiry);
    };

    Credit.prototype.cardNumberInput = function(input) {
      this.listen(input, 'keypress', this.restrictNumeric);
      this.listen(input, 'keypress', this.restrictCardNumber);
      this.listen(input, 'keypress', this.formatCardNumber);
      this.listen(input, 'keydown', this.formatBackCardNumber);
      this.listen(input, 'paste', this.reFormatCardNumber);
      this.listen(input, 'change', this.reFormatCardNumber);
      return this.listen(input, 'input', this.reFormatCardNumber);
    };

    Credit.prototype.numericInput = function(input) {
      this.listen(input, 'keypress', this.restrictNumeric);
      this.listen(input, 'paste', this.restrictNumeric);
      this.listen(input, 'change', this.restrictNumeric);
      return this.listen(input, 'input', this.restrictNumeric);
    };

    Credit.prototype.parseCardExpiry = function(value) {
      var month, prefix, ref, year;
      value = value.replace(/\s/g, '');
      ref = value.split('/', 2), month = ref[0], year = ref[1];
      if ((year != null ? year.length : void 0) === 2 && /^\d+$/.test(year)) {
        prefix = (new Date).getFullYear();
        prefix = prefix.toString().slice(0, 2);
        year = prefix + year;
      }
      month = parseInt(month, 10);
      year = parseInt(year, 10);
      return {
        month: month,
        year: year
      };
    };

    Credit.prototype.validateCardNumber = function(num) {
      var card, ref;
      num = (num + '').replace(/\s+|-/g, '');
      if (!/^\d+$/.test(num)) {
        return false;
      }
      card = cardFromNumber(num);
      if (!card) {
        return false;
      }
      return (ref = num.length, indexOf.call(card.length, ref) >= 0) && (card.luhn === false || luhnCheck(num));
    };

    Credit.prototype.validateCardExpiry = function(month, year) {
      var currentTime, expiry, ref;
      if (typeof month === 'object' && 'month' in month) {
        ref = month, month = ref.month, year = ref.year;
      }
      if (!(month && year)) {
        return false;
      }
      month = String(month).trim();
      year = String(year).trim();
      if (!/^\d+$/.test(month)) {
        return false;
      }
      if (!/^\d+$/.test(year)) {
        return false;
      }
      if (!((1 <= month && month <= 12))) {
        return false;
      }
      if (year.length === 2) {
        if (year < 70) {
          year = "20" + year;
        } else {
          year = "19" + year;
        }
      }
      if (year.length !== 4) {
        return false;
      }
      expiry = new Date(year, month);
      currentTime = new Date;
      expiry.setMonth(expiry.getMonth() - 1);
      expiry.setMonth(expiry.getMonth() + 1, 1);
      return expiry > currentTime;
    };

    Credit.prototype.validateCardCVC = function(cvc, type) {
      var card, ref;
      cvc = String(cvc).trim();
      if (!/^\d+$/.test(cvc)) {
        return false;
      }
      card = this.cardFromType(type);
      if (card != null) {
        return ref = cvc.length, indexOf.call(card.cvcLength, ref) >= 0;
      } else {
        return cvc.length >= 3 && cvc.length <= 4;
      }
    };

    Credit.prototype.parseCardType = function(num) {
      var ref;
      if (!num) {
        return null;
      }
      return ((ref = this.cardFromNumber(num)) != null ? ref.type : void 0) || null;
    };

    Credit.prototype.formatCardNumber = function(num) {
      var card, groups, ref, upperLength;
      num = this.replaceFullWidthChars(num);
      num = num.replace(/\D/g, '');
      card = this.cardFromNumber(num);
      if (!card) {
        return num;
      }
      upperLength = card.length[card.length.length - 1];
      num = num.slice(0, upperLength);
      console.log('Credit.formatCardNumber()', card.type, card.format.toString(), num);
      if (card.format.global) {
        return (ref = num.match(card.format)) != null ? ref.join(' ') : void 0;
      } else {
        groups = card.format.exec(num);
        if (groups == null) {
          return;
        }
        groups.shift();
        groups = groups.filter(Boolean);
        return groups.join(' ');
      }
    };

    Credit.prototype.formatCardExpiry = function(expiry) {
      var mon, parts, sep, year;
      expiry = this.replaceFullWidthChars(expiry);
      parts = expiry.match(/^\D*(\d{1,2})(\D+)?(\d{1,4})?/);
      if (!parts) {
        return '';
      }
      mon = parts[1] || '';
      sep = parts[2] || '';
      year = parts[3] || '';
      if (year.length > 0) {
        sep = ' / ';
      } else if (sep === ' /') {
        mon = mon.substring(0, 1);
        sep = '';
      } else if (mon.length === 2 || sep.length > 0) {
        sep = ' / ';
      } else if (mon.length === 1 && (mon !== '0' && mon !== '1')) {
        mon = "0" + mon;
        sep = ' / ';
      }
      return mon + sep + year;
    };

    return Credit;

  })();

}).call(this);
