// Generated by CoffeeScript 1.12.2
(function() {
  var Credit;

  Credit = (function() {
    module.exports = Credit;

    Credit.Cards = require('data/cards.json');

    Credit.AmericanExpressFormat = "/(\d{1,4})(\d{1,6})?(\d{1,5})?/";

    Credit.DinersClubFormat = "/(\d{1,4})(\d{1,6})?(\d{1,4})?/";

    Credit.Unknown = {
      type: "Unknown",
      patterns: [],
      format: "defaultFormat",
      length: [16],
      cvcLength: [],
      luhn: true
    };

    function Credit(selector) {
      this.selector = selector;
    }

    Credit.prototype.ready = function() {};

    Credit.prototype.cardFromNumber = function(num) {
      var card, i, j, len, len1, p, pattern, ref, ref1;
      num = (num + '').replace(/\D/g, '');
      ref = Credit.Cards;
      for (i = 0, len = ref.length; i < len; i++) {
        card = ref[i];
        ref1 = card.patterns;
        for (j = 0, len1 = ref1.length; j < len1; j++) {
          pattern = ref1[j];
          p = pattern + '';
          if (num.substr(0, p.length) === p) {
            return card;
          }
        }
      }
      return Credit.Unknown;
    };

    Credit.prototype.cardFromType = function(type) {
      var card, i, len, ref;
      ref = Credit.Cards;
      for (i = 0, len = ref.length; i < len; i++) {
        card = ref[i];
        if (card.type === type) {
          return card;
        }
      }
    };

    return Credit;

  })();

}).call(this);
