// Generated by CoffeeScript 1.12.2
(function() {
  var Cust;

  Cust = (function() {
    module.exports = Cust;

    Cust.Data = require('data/Cust.json');

    function Cust() {}

    return Cust;

  })();

}).call(this);
