// Generated by CoffeeScript 1.12.2
(function() {
  var Guest;

  Guest = (function() {
    function Guest() {}

    module.exports = Guest;

    Guest.init = function() {
      return Util.ready(function() {
        var Alloc, Book, Cust, Data, Firestore, Master, Room, Stream, alloc, book, cust, master, room, store, stream;
        Stream = require('js/store/Stream');
        Firestore = require('js/store/Firestore');
        Data = require('js/res/Data');
        Room = require('js/res/Room');
        Cust = require('js/res/Cust');
        Book = require('js/res/Book');
        Master = require('js/res/Master');
        Alloc = require('js/res/Alloc');
        stream = new Stream([]);
        store = new Firestore(stream, "skytest", Data.configSkytest);
        room = new Room(stream, store);
        cust = new Cust(stream, store);
        book = new Book(stream, store, room, cust);
        master = new Master(stream, store, room, cust, book);
        alloc = new Alloc(stream, store, room, cust, master, book);
        book.ready();
        return master.ready();
      });
    };

    return Guest;

  })();

  Guest.init();

}).call(this);
