// Generated by CoffeeScript 1.12.2
(function() {
  var $, Home,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    hasProp = {}.hasOwnProperty;

  $ = require('jquery');

  Home = (function() {
    module.exports = Home;

    function Home(stream, store, room1, pict) {
      this.stream = stream;
      this.store = store;
      this.room = room1;
      this.pict = pict;
      this.onMakeRes = bind(this.onMakeRes, this);
      this.rooms = this.room.rooms;
      this.roomUIs = this.room.roomUIs;
    }

    Home.prototype.ready = function(book) {
      this.book = book;
      $('#MakeRes').click(this.onMakeRes);
      $('#MapDirs').click((function(_this) {
        return function() {
          return Util.toPage('rooms/X.html');
        };
      })(this));
      $('#Contact').click((function(_this) {
        return function() {
          return Util.toPage('rooms/Y.html');
        };
      })(this));
      this.listRooms();
      this.pict.createSlideShow('M', 600, 600);
    };

    Home.prototype.listRooms = function() {
      var htm, ref, room, roomId;
      $('#Slides').css({
        left: "20%",
        width: "80%"
      });
      htm = "<div class=\"HomeSee\">Enjoy Everything Skyline has to Offer</div>";
      htm += "<div class=\"RoomSee\">See Our Cottages</div>";
      htm += "<ul  class=\"RoomUL\">";
      ref = this.rooms;
      for (roomId in ref) {
        if (!hasProp.call(ref, roomId)) continue;
        room = ref[roomId];
        htm += "<li class=\"RoomLI\"><a href=\"rooms/" + roomId + ".html\">" + room.name + "</a></li>";
      }
      htm += "</ul>";
      $("#Viewer").append(htm);
    };

    Home.prototype.onMakeRes = function() {
      $('#Viewer').hide();
      this.book.ready();
    };

    return Home;

  })();

}).call(this);
