// Generated by CoffeeScript 1.12.2
(function() {
  var $, Home,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  $ = require('jquery');

  Home = (function() {
    module.exports = Home;

    function Home(stream, store, room, pict) {
      this.stream = stream;
      this.store = store;
      this.room = room;
      this.pict = pict;
      this.onMakeRes = bind(this.onMakeRes, this);
      this.rooms = this.room.rooms;
      this.roomUIs = this.room.roomUIs;
    }

    Home.prototype.ready = function(book) {
      this.book = book;
      $('#MakeRes').click(this.onMakeRes);
      return this.pict.createSlideShow('M', 600, 600);
    };

    Home.prototype.onMakeRes = function() {
      $('#Viewer').hide();
      return this.book.ready();
    };

    return Home;

  })();

}).call(this);
