// Generated by CoffeeScript 1.12.2
(function() {
  var $, Home,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    hasProp = {}.hasOwnProperty;

  $ = require('jquery');

  Home = (function() {
    module.exports = Home;

    function Home(stream, store, room1, pict) {
      this.stream = stream;
      this.store = store;
      this.room = room1;
      this.pict = pict;
      this.onMakeRes = bind(this.onMakeRes, this);
      this.rooms = this.room.rooms;
      this.roomUIs = this.room.roomUIs;
    }

    Home.prototype.ready = function(book) {
      this.book = book;
      $('#MakeRes').click(this.onMakeRes);
      $('#MapDirs').click((function(_this) {
        return function() {
          return Util.toPage('rooms/X.html');
        };
      })(this));
      $('#Contact').click((function(_this) {
        return function() {
          return Util.toPage('rooms/Y.html');
        };
      })(this));
      $('#Head').append(this.headHtml());
      this.listRooms();
      this.pict.createSlideShow('M', 600, 600);
    };

    Home.prototype.headHtml = function() {
      return "<ul class=\"Head1\">\n <li>Trout Fishing</li>\n <li>Bring your Pet</li>\n</ul>\n<ul class=\"Head2\">\n  <li>Near YMCA</li>\n  <li>Hiking</li>\n</ul>\n<ul class=\"Head3\">\n  <li>Free Parking</li>\n  <li>3 Private Spas</li>\n</ul>\n<ul class=\"Head4\">\n  <li>WiFi in Cabins 1-8</li>\n  <li>All Non-Smoking Cabins</li>\n</ul>";
    };

    Home.prototype.listRooms = function() {
      var htm, ref, room, roomId;
      $('#Slides').css({
        left: "22%",
        width: "78%"
      });
      htm = "<div class=\"HomeSee\">Enjoy Everything Skyline Has to Offer</div>";
      htm += "<div class=\"RoomSee\">See Our Cottages</div>";
      htm += "<ul  class=\"RoomUL\">";
      ref = this.rooms;
      for (roomId in ref) {
        if (!hasProp.call(ref, roomId)) continue;
        room = ref[roomId];
        htm += "<li class=\"RoomLI\"><a href=\"rooms/" + roomId + ".html\">" + room.name + "</a></li>";
      }
      htm += "</ul>";
      $("#View").append(htm);
    };

    Home.prototype.hideMkt = function() {
      $('#Navb').hide();
      $('#Head').hide();
      return $('#View').hide();
    };

    Home.prototype.onMakeRes = function() {
      this.hideMkt();
      this.book.ready();
    };

    return Home;

  })();

}).call(this);
