// Generated by CoffeeScript 1.12.2
(function() {
  var Owner;

  Owner = (function() {
    function Owner() {}

    module.exports = Owner;

    Owner.init = function() {
      return Util.ready(function() {
        var Data, Fire, Master, Memory, Pay, Res, Stream, master, pay, res, store, stream;
        Stream = require('js/store/Stream');
        Fire = require('js/store/Fire');
        Memory = require('js/store/Memory');
        Data = require('js/res/Data');
        Res = require('js/res/Res');
        Pay = require('js/res/Pay');
        Master = require('js/res/Master');
        stream = new Stream([]);
        store = new Fire(stream, "skyline", Data.configSkyline);
        res = new Res(stream, store, Data, 'Owner');
        pay = new Pay(stream, store, Data, res);
        master = new Master(stream, store, Data, res, pay);
        return master.ready();
      });
    };

    return Owner;

  })();

  Owner.init();

}).call(this);
