// Generated by CoffeeScript 1.12.2
(function() {
  var Owner;

  Owner = (function() {
    function Owner() {}

    module.exports = Owner;

    Owner.init = function() {
      return Util.ready(function() {
        var Data, Fire, Master, Res, Stream, master, res, store, stream;
        Stream = require('js/store/Stream');
        Fire = require('js/store/Fire');
        Data = require('js/res/Data');
        Res = require('js/res/Res');
        Master = require('js/res/Master');
        stream = new Stream([]);
        store = new Fire(stream, "skytest", Data.configSkytest);
        res = new Res(stream, store, Data);
        master = new Master(stream, store, Data, res);
        return master.ready();
      });
    };

    return Owner;

  })();

  Owner.init();

}).call(this);
