// Generated by CoffeeScript 1.12.2
(function() {
  var $, Img, Pict;

  $ = require('jquery');

  Img = require('data/Img.json');

  Pict = (function() {
    module.exports = Pict;

    function Pict(stream, store, room, Data) {
      this.stream = stream;
      this.store = store;
      this.room = room;
      this.Data = Data;
    }

    Pict.prototype.createSlideShow = function(roomId) {
      var dir, htm, i, len, pic, ref;
      htm = "";
      dir = Img[roomId].dir;
      ref = Img[roomId].pics;
      for (i = 0, len = ref.length; i < len; i++) {
        pic = ref[i];
        Util.log("Pict.createSlideShow()", pic);
        htm += this.li(pic, dir);
      }
      $('#slideshow').append(htm);
    };

    Pict.prototype.li = function(pic, dir) {
      return "<li><h3>" + pic.name + "</h3><span>" + dir + pic.src + "</span><p>" + pic.p + "</p><a href=\"#\"><img src=\"" + dir + pic.src + "\", width=\"100\" alt=\"" + pic.name + "\"/></a></li>";
    };

    return Pict;

  })();

}).call(this);
