// Generated by CoffeeScript 1.12.2
(function() {
  var $, Pict,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  $ = Util.requireModule('jquery', 'skyline');

  Pict = (function() {
    if ((typeof module !== "undefined" && module !== null) && (module.exports != null)) {
      module.exports = Pict;
    }

    window.Pict = Pict;

    Pict.page = function(title, prev, curr, next) {
      var pict;
      pict = new Pict();
      Util.ready(function() {
        pict.roomPageHtml(title, prev, next);
        pict.createSlideShow('RoomSlides', curr, 600, 600);
      });
    };

    function Pict() {
      this.onSlides = bind(this.onSlides, this);
      this.onVideo = bind(this.onVideo, this);
    }

    Pict.prototype.roomPageHtml = function(title, prev, next) {
      var htm, nextPage, prevPage;
      prevPage = " '" + prev + ".html' ";
      nextPage = " '" + next + ".html' ";
      htm = "<button class=\"prev\" onclick=\"Util.toPage(" + prevPage + ");\"    >Prev Room</button>\n<span   class=\"room\">" + title + "</span>\n<button class=\"next\" onclick=\"Util.toPage(" + nextPage + ");\"    >Next Room</button>\n<button class=\"home\" onclick=\"Util.toPage('../index.html');\">Home Page</button>";
      $('#top').append(htm);
    };

    Pict.prototype.createSlideShow = function(parentId, roomId, w, h) {
      var images, url;
      $('#' + parentId).append(this.wrapperHtml());
      images = (function(_this) {
        return function(Img) {
          var dir, htm, i, len, pic, ref;
          htm = "";
          dir = Img[roomId].dir;
          ref = Img[roomId]['pics'];
          for (i = 0, len = ref.length; i < len; i++) {
            pic = ref[i];
            htm += _this.li(pic, dir);
          }
          $('#slideshow').append(htm);
          return _this.initTINY(w, h);
        };
      })(this);
      url = roomId === 'M' ? "../data/Img.json" : "../../data/Img.json";
      $.getJSON(url, images);
    };

    Pict.prototype.li = function(pic, dir) {
      return "<li><h3>" + pic.name + "</h3><span>" + dir + pic.src + "</span><p>" + pic.p + "</p><a href=\"#\"><img src=\"" + dir + pic.src + "\" width=\"100\" height=\"70\" alt=\"" + pic.name + "\"/></a></li>";
    };

    Pict.prototype.onVideo = function() {
      window.slideshow.auto = false;
      $('#Slides').hide();
      $('#Video').show();
      $('#ViewVid').show();
      $('#VideoSee').text('View Slides').click(this.onSlides);
    };

    Pict.prototype.onSlides = function() {
      $('#ViewVid').hide();
      $('#Slides').show();
      window.slideshow.auto = true;
      $('#VideoSee').text('View Video').click(this.onVideo);
    };

    Pict.prototype.wrapperHtml = function() {
      return "<ul id=\"slideshow\"></ul>\n<div id=\"wrapper\">\n  <div id=\"fullsize\">\n    <div id=\"imgprev\" class=\"imgnav\" title=\"Previous Image\"></div>\n    <div id=\"imglink\"></div>\n    <div id=\"imgnext\" class=\"imgnav\" title=\"Next Image\"></div>\n    <div id=\"image\"></div>\n    <div id=\"information\">\n      <h3></h3>\n      <p></p>\n    </div>\n  </div>\n  <div id=\"thumbnails\">\n    <div id=\"slideleft\" title=\"Slide Left\"></div>\n    <div id=\"slidearea\">\n      <div id=\"slider\"></div>\n    </div>\n    <div id=\"slideright\" title=\"Slide Right\"></div>\n  </div>\n</div>";
    };

    Pict.prototype.initTINY = function(w, h) {
      var slideshow;
      Util.noop(w, h);
      TINY.ElemById('slideshow').style.display = 'none';
      TINY.ElemById('wrapper').style.display = 'block';
      window.slideshow = new TINY.slideshow("slideshow");
      slideshow = window.slideshow;
      slideshow.auto = false;
      slideshow.speed = 10;
      slideshow.link = "linkhover";
      slideshow.info = "information";
      slideshow.thumbs = "slider";
      slideshow.left = "slideleft";
      slideshow.right = "slideright";
      slideshow.scrollSpeed = 4;
      slideshow.spacing = 5;
      slideshow.active = "#fff";
      return slideshow.init("slideshow", "image", "imgprev", "imgnext", "imglink");
    };

    Pict.prototype.resizeSlideView = function(w, h) {
      $('#wrapper').css({
        width: w,
        height: h
      });
      $('#fullsize').css({
        width: w,
        height: h - 100
      });
      $('#slidearea').css({
        width: w - 45,
        height: 61
      });
      $('#image').css({
        width: w - 100,
        height: h - 200
      });
      $('#image img').css({
        width: w - 100,
        height: h - 200
      });
      slideshow.width = w - 100;
      slideshow.height = h - 200;
    };

    return Pict;

  })();

}).call(this);
