// Generated by CoffeeScript 1.6.3
(function() {
  var $, Data, Query, UI;

  $ = require('jquery');

  Data = require('js/res/Data');

  UI = require('js/res/UI');

  Query = (function() {
    module.exports = Query;

    function Query(stream, store, res, master) {
      this.stream = stream;
      this.store = store;
      this.res = res;
      this.master = master;
    }

    Query.prototype.readyQuery = function() {
      $('#ResTbl').empty();
      $('#ResTbl').append(this.resvHead());
      this.resvSortClick('RHBooked', 'booked');
      this.resvSortClick('RHRoom', 'roomId');
      this.resvSortClick('RHArrive', 'arrive');
      this.resvSortClick('RHStayTo', 'stayto');
      this.resvSortClick('RHName', 'last');
      this.resvSortClick('RHStatus', 'status');
      this.updateBody(this.master.begQuery(), Data.toDateStr(Data.numDaysMonth()), 'arrive');
    };

    Query.prototype.updateBody = function(beg, end, prop) {
      var resvs;
      $('#QArrive').text(Data.toMMDD(beg));
      $('#QStayTo').text(Data.toMMDD(end));
      resvs = [];
      if (prop === 'depart') {
        resvs = this.res.resvArrayDepart();
      }
      if (end != null) {
        resvs = this.res.resvArrayByProp(beg, end, prop);
      } else {
        resvs = this.res.resvArrayByDate(beg);
      }
      return this.resvBody(resvs);
    };

    Query.prototype.resvSortClick = function(id, prop) {
      var _this = this;
      return $('#' + id).click(function() {
        return _this.resvBody(_this.res.resvArrayByProp(_this.master.dateBeg, _this.master.dateEnd, prop));
      });
    };

    Query.prototype.resvHead = function() {
      var htm;
      htm = "";
      htm += "<table class=\"RTTable\"><thead><tr>";
      htm += "<th id=\"RHArrive\">Arrive</th><th id=\"RHStayTo\">Stay To</th><th id=\"RHNights\">Nights</th><th id=\"RHRoom\"  >Room</th>";
      htm += "<th id=\"RHName\"  >Name</th>  <th id=\"RHGuests\">Guests</th> <th id=\"RHStatus\">Status</th><th id=\"RHBooked\">Booked</th>";
      htm += "<th id=\"RHPrice\" >Price</th> <th id=\"RHTotal\" >Total</th>  <th id=\"RHCommis\">Comm</th>  <th id=\"RHTax\"  >Tax</th>";
      htm += "<th id=\"RHCharge\">Charge</th>";
      htm += "</tr><tr>";
      htm += "<th id=\"QArrive\"></th><th id=\"QStayTo\"></th><th></th><th></th>";
      htm += "<th></th><th></th><th></th><th></th><th></th><th></th><th></th><th></th>";
      htm += "</tr></thead><tbody id=\"RTBody\"></tbody></table>";
      return htm;
    };

    Query.prototype.resvBody = function(resvs) {
      var arrive, booked, charge, charges, commis, commiss, htm, r, stayto, tax, taxes, totals, trClass, _i, _len;
      $('#RTBody').empty();
      htm = "";
      totals = 0;
      taxes = 0;
      commiss = 0;
      charges = 0;
      for (_i = 0, _len = resvs.length; _i < _len; _i++) {
        r = resvs[_i];
        arrive = Data.toMMDD(r.arrive);
        stayto = Data.toMMDD(r.stayto);
        booked = Data.toMMDD(r.booked);
        commis = r.status === 'Booking' || r.status === 'Prepaid' ? '$' + Util.toFixed(r.total * Data.commis) : '';
        tax = Util.toFixed(r.total * Data.tax);
        charge = Util.toFixed(r.total + parseFloat(tax));
        trClass = 'RTOldRow';
        htm += "<tr class=\"" + trClass + "\">";
        htm += "<td class=\"RTArrive\">" + arrive + "  </td><td class=\"RTStayto\">" + stayto + "</td><td class=\"RTNights\">" + r.nights + "</td>";
        htm += "<td class=\"RTRoomId\">" + r.roomId + "</td><td class=\"RTLast\"  >" + r.last + "</td><td class=\"RTGuests\">" + r.guests + "</td>";
        htm += "<td class=\"RTStatus\">" + r.status + "</td><td class=\"RTBooked\">" + booked + "</td><td class=\"RTPrice\" >$" + r.price + "</td>";
        htm += "<td class=\"RTTotal\" >$" + r.total + "</td><td class=\"RTCommis\">" + commis + "</td><td class=\"RTTax\"   >$" + tax + "    </td>";
        htm += "<td class=\"RTCharge\">$" + charge + " </td></tr>";
        totals += r.total;
        taxes += r.total * Data.tax;
        if (r.status === 'Booking' || r.status === 'Prepaid') {
          commiss += r.total * Data.commis;
        }
        charges += r.total + parseFloat(tax);
      }
      taxes = Util.toFixed(taxes);
      commiss = Util.toFixed(commiss);
      charges = Util.toFixed(charges);
      htm += "<tr class=\"'RTTotRow'\">";
      htm += "<td class=\"RTArrive\">          </td><td class=\"RTStayto\">          </td><td class=\"RTNights\">         </td>";
      htm += "<td class=\"RTRoomId\">          </td><td class=\"RTLast\"  >          </td><td class=\"RTGuests\">         </td>";
      htm += "<td class=\"RTStatus\">          </td><td class=\"RTBooked\">          </td><td class=\"RTPrice\" >         </td>";
      htm += "<td class=\"RTTotal\" >$" + totals + "</td><td class=\"RTCommis\">" + commiss + "</td><td class=\"RTTax\"   >$" + taxes + "</td>";
      htm += "<td class=\"RTCharge\">$" + charges + "</td></tr>";
      $('#RTBody').append(htm);
    };

    return Query;

  })();

}).call(this);
