// Generated by CoffeeScript 1.12.2
(function() {
  var $, Query;

  $ = require('jquery');

  Query = (function() {
    module.exports = Query;

    function Query(stream, store, Data, res) {
      this.stream = stream;
      this.store = store;
      this.Data = Data;
      this.res = res;
    }

    return Query;

  })();

}).call(this);
