// Generated by CoffeeScript 1.12.2
(function() {
  var Room,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    hasProp = {}.hasOwnProperty;

  Room = (function() {
    module.exports = Room;

    Room.Rooms = require('data/Room.json');

    Room.States = ["book", "depo", "hold", "free"];

    function Room(stream, store) {
      this.stream = stream;
      this.store = store;
      this.onAlloc = bind(this.onAlloc, this);
      this.initRooms = bind(this.initRooms, this);
      this.rooms = Room.Rooms;
      this.states = Room.States;
      this.roomUIs = this.createRoomUIs(this.rooms);
      this.initRooms();
    }

    Room.prototype.createRoomUIs = function(data) {
      var key, room, roomUIs;
      roomUIs = {};
      for (key in data) {
        room = data[key];
        roomUIs[key] = {};
      }
      return roomUIs;
    };

    Room.prototype.initRooms = function() {
      this.store.subscribe('Room', 'none', 'make', (function(_this) {
        return function(make) {
          _this.store.insert('Room', _this.rooms);
          return Util.noop(make);
        };
      })(this));
      return this.store.make('Room');
    };

    Room.prototype.dayBooked = function(room, date) {
      var day;
      day = room.days[date];
      if (day != null) {
        return day.status;
      } else {
        return 'free';
      }
    };

    Room.prototype.onAlloc = function(alloc, roomId) {
      var day, obj, ref, room;
      room = this.rooms[roomId];
      ref = alloc.days;
      for (day in ref) {
        if (!hasProp.call(ref, day)) continue;
        obj = ref[day];
        room.days[day] = alloc.days[day];
      }
      this.store.put('Room', roomId, room);
    };

    return Room;

  })();

}).call(this);
