// Generated by CoffeeScript 1.12.2
(function() {
  var Test,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Test = (function() {
    module.exports = Test;

    function Test(stream, store, room) {
      this.stream = stream;
      this.store = store;
      this.room = room;
      this.west = bind(this.west, this);
      this.onDel = bind(this.onDel, this);
      this.onPut = bind(this.onPut, this);
      this.onAdd = bind(this.onAdd, this);
      this.del = bind(this.del, this);
      this.put = bind(this.put, this);
      this.get = bind(this.get, this);
      this.add = bind(this.add, this);
      this.select = bind(this.select, this);
      this.remove = bind(this.remove, this);
      this.update = bind(this.update, this);
      this.insert = bind(this.insert, this);
      this.drop = bind(this.drop, this);
      this.show = bind(this.show, this);
      this.make = bind(this.make, this);
      this.rooms = this.room.rooms;
    }

    Test.prototype.subscribe = function() {
      this.store.subscribe('Room', 'none', 'make', (function(_this) {
        return function(make) {
          Util.log('Room.make()', make);
          return _this.insert();
        };
      })(this));
      this.store.subscribe('Room', 'none', 'insert', (function(_this) {
        return function(insert) {
          Util.log('Room.insert()', insert);
          return _this.update();
        };
      })(this));
      this.store.subscribe('Room', 'none', 'update', (function(_this) {
        return function(update) {
          Util.log('Room.update()', update);
          return _this.remove();
        };
      })(this));
      this.store.subscribe('Room', 'none', 'remove', (function(_this) {
        return function(remove) {
          Util.log('Room.remove()', remove);
          return _this.select();
        };
      })(this));
      this.store.subscribe('Room', 'none', 'select', (function(_this) {
        return function(select) {
          Util.logObjs('Room.select()', select);
          _this.onAdd();
          _this.onPut();
          _this.onDel();
          return _this.add();
        };
      })(this));
      this.store.subscribe('Room', 'none', 'onAdd', (function(_this) {
        return function(onAdd) {
          return Util.log('Room.onAdd()', onAdd);
        };
      })(this));
      this.store.subscribe('Room', 'none', 'onPut', (function(_this) {
        return function(onPut) {
          return Util.log('Room.onPut()', onPut);
        };
      })(this));
      this.store.subscribe('Room', 'none', 'onDel', (function(_this) {
        return function(onDel) {
          return Util.log('Room.onDel()', onDel);
        };
      })(this));
      this.store.subscribe('Room', 'W', 'add', (function(_this) {
        return function(add) {
          Util.log('Room.add()', add);
          return _this.get();
        };
      })(this));
      this.store.subscribe('Room', 'S', 'get', (function(_this) {
        return function(get) {
          Util.log('Room.get()', get);
          return _this.put();
        };
      })(this));
      this.store.subscribe('Room', '7', 'put', (function(_this) {
        return function(put) {
          Util.log('Room.put()', put);
          return _this.del();
        };
      })(this));
      this.store.subscribe('Room', '8', 'del', (function(_this) {
        return function(del) {
          Util.log('Room.del()', del);
          return _this.show();
        };
      })(this));
      this.store.subscribe('Room', 'none', 'show', (function(_this) {
        return function(show) {
          return Util.log('Room.show()', show);
        };
      })(this));
      return this.store.subscribe('Room', 'none', 'drop', (function(_this) {
        return function(drop) {
          return Util.log('Room.drop()', drop);
        };
      })(this));
    };

    Test.prototype.make = function() {
      return this.store.make('Room');
    };

    Test.prototype.show = function() {
      this.store.show('Room');
      return this.store.show();
    };

    Test.prototype.drop = function() {
      return this.store.drop('Room');
    };

    Test.prototype.insert = function() {
      return this.store.insert('Room', this.rooms);
    };

    Test.prototype.update = function() {
      var updt;
      updt = {};
      updt['1'] = this.rooms['1'];
      updt['2'] = this.rooms['2'];
      updt['3'] = this.rooms['3'];
      updt['1'].max = 14;
      updt['2'].max = 14;
      updt['3'].max = 14;
      return this.store.update('Room', updt);
    };

    Test.prototype.remove = function() {
      return this.store.remove('Room', ['4', '5', '6']);
    };

    Test.prototype.select = function() {
      return this.store.select('Room');
    };

    Test.prototype.add = function() {
      return this.store.add('Room', "W", this.west());
    };

    Test.prototype.get = function() {
      return this.store.get('Room', "S");
    };

    Test.prototype.put = function() {
      return this.store.put('Room', "7", this.west());
    };

    Test.prototype.del = function() {
      return this.store.del('Room', "8");
    };

    Test.prototype.onAdd = function() {
      return this.store.on('Room', 'onAdd');
    };

    Test.prototype.onPut = function() {
      return this.store.on('Room', 'onPut');
    };

    Test.prototype.onDel = function() {
      return this.store.on('Room', 'onDel');
    };

    Test.prototype.west = function() {
      return {
        "key": "W",
        "name": "West Skyline",
        "pet": 12,
        "spa": 0,
        "max": 4,
        "price": 0,
        "1": 135,
        "2": 135,
        "3": 145,
        "4": 155
      };
    };

    return Test;

  })();

}).call(this);
